import { createContext, useContext, useState, useEffect } from 'react';

// Translations for all UI elements
const translations = {
  en: {
    // Navigation
    nav_home: 'Home',
    nav_dashboard: 'My Catalog',
    nav_demo: 'Try Demo',
    nav_login: 'Login',
    nav_signup: 'Sign Up',
    nav_logout: 'Logout',
    // Landing
    hero_title: 'AI-Powered Digital Catalog for Local Sellers',
    hero_subtitle: 'Create professional product listings using voice in your language',
    get_started: 'Get Started Free',
    try_demo: 'Try Demo',
    choose_language: 'Choose your language',
    free_to_use: 'Free to Use',
    indian_languages: '6 Indian Languages',
    ai_powered: 'AI-Powered',
    accessibility_ready: 'Accessibility Ready',
    voice_commands_enabled: 'Voice Commands Enabled',
    voice_commands_help: 'Say "Help" to learn voice commands • Accessible for visually impaired users',
    powerful_features: 'Powerful Features for Small Businesses',
    features_subtitle: 'Everything you need to create professional product catalogs without any technical knowledge',
    feature_voice_title: 'Voice Input',
    feature_voice_desc: 'Simply speak to describe your products. Our AI understands Hindi, Tamil, Telugu, Kannada, Bengali, and English.',
    feature_photo_title: 'Photo Capture',
    feature_photo_desc: 'Take a photo of your product and let AI generate the description automatically.',
    feature_ai_title: 'AI Descriptions',
    feature_ai_desc: 'Get professional product descriptions, categories, and pricing suggestions instantly.',
    feature_multilang_title: 'Multi-Language',
    feature_multilang_desc: 'Create catalogs in your local language. Auto-translate to reach more customers.',
    feature_mobile_title: 'Mobile-First',
    feature_mobile_desc: 'Designed for smartphones. Easy to use even with basic phones and slow internet.',
    feature_share_title: 'Share Anywhere',
    feature_share_desc: 'Share your catalog link on WhatsApp, Facebook, or any platform to reach customers.',
    challenges_title: 'Challenges We Solve',
    challenges_subtitle: 'Small businesses face real barriers to going digital',
    challenge_skills_title: 'Low Digital Skills',
    challenge_skills_desc: 'Many shopkeepers find technology confusing. Complex apps and forms are overwhelming.',
    challenge_skills_solution: 'Our voice-first approach needs no typing or technical knowledge.',
    challenge_language_title: 'Language Barriers',
    challenge_language_desc: 'Most digital tools are in English, excluding millions who prefer local languages.',
    challenge_language_solution: 'Full support for Hindi, Tamil, Telugu, Kannada, Bengali, and English.',
    challenge_presence_title: 'No Online Presence',
    challenge_presence_desc: 'Without a catalog, businesses miss opportunities to reach new customers online.',
    challenge_presence_solution: 'Create shareable catalogs in minutes, not days.',
    how_it_works: 'How It Works',
    how_it_works_subtitle: 'Create your first product listing in under 2 minutes',
    step1_title: 'Choose Language',
    step1_desc: 'Select your preferred language from 6 Indian languages',
    step2_title: 'Describe Product',
    step2_desc: 'Speak, type, or take a photo of your product',
    step3_title: 'AI Generates',
    step3_desc: 'AI creates professional name, description & category',
    step4_title: 'Share Catalog',
    step4_desc: 'Share your catalog link with customers',
    stat_languages: 'Languages Supported',
    stat_inputs: 'Input Methods',
    stat_categories: 'Product Categories',
    stat_products: 'Products You Can Add',
    cta_title: 'Ready to Digitize Your Business?',
    cta_subtitle: 'Join thousands of small businesses already using Digital Catalog Agent. It\'s free, easy, and works in your language.',
    cta_button: 'Create Your Catalog Now',
    cta_footer: 'Supporting Digital India initiative • Made for Bharat 🇮🇳',
    // Dashboard
    my_catalog: 'My Catalog',
    products_count: 'products',
    publish_platforms: 'Publish to Platforms',
    add_product: 'Add Product',
    no_products: 'No products yet. Start by adding your first product!',
    add_first: 'Add Your First Product',
    edit: 'Edit',
    delete: 'Delete',
    deleting: 'Deleting...',
    // Add Product
    add_new_product: 'Add New Product',
    product_name: 'Product Name',
    description: 'Description',
    category: 'Category',
    price: 'Price',
    language: 'Language',
    save_product: 'Save Product',
    saving: 'Saving...',
    select_language: 'Select Your Language',
    describe_method: 'How would you like to describe your product?',
    voice: 'Voice',
    text: 'Text',
    camera: 'Camera',
    speak_to_describe: 'Speak to describe',
    type_description: 'Type description',
    take_a_photo: 'Take a photo',
    describe_product: 'Describe your product',
    describe_placeholder: 'E.g., "Handmade cotton saree with traditional block print design from Rajasthan, perfect for festivals..."',
    add_description_photo: 'Add a description for better AI results',
    describe_photo: 'Describe what\'s in the photo...',
    generate_with_ai: 'Generate Product Details with AI',
    ai_generating: 'AI is generating...',
    ai_success: '✨ AI generated English product listing from your voice input! Review and edit below.',
    review_edit: 'Review & Edit Details',
    back_to_input: '← Back to Input',
    product_image: 'Product Image',
    enter_product_name: 'Enter product name',
    describe_your_product: 'Describe your product',
    select_category: 'Select category',
    enter_price: 'Enter price',
    cancel: 'Cancel',
    add_to_catalog: '✓ Add Product to Catalog',
    adding_product: 'Adding Product...',
    tip_describe: '💡 Tip: Describe your product in detail for better AI-generated listings',
    supports_voice: 'Supports voice input in Hindi, Tamil, Telugu, Kannada, and Bengali',
    step_describe: 'Describe',
    step_review: 'Review & Save',
    please_describe: 'Please describe your product first using voice or text',
    failed_generate: 'Failed to generate product details. Please try again.',
    // Voice
    voice_input: 'Voice Input',
    tap_to_speak: 'Tap to speak',
    listening: 'Listening...',
    stop: 'Stop',
    // Camera
    take_photo: 'Take Photo',
    upload_image: 'Upload Image',
    capture: 'Capture',
    retake: 'Retake',
    use_photo: 'Use Photo',
    // Export
    publish_title: 'Publish to Seller Platforms',
    publish_subtitle: 'Export your catalog to major e-commerce platforms',
    your_catalog: 'Your Catalog',
    products_ready: 'products ready to publish',
    view_products: 'View Products',
    share_link: 'Shareable Catalog Link',
    share_link_desc: 'Share this link with customers',
    copy: 'Copy',
    copied: 'Copied!',
    export: 'Export',
    exporting: 'Exporting...',
    exported: 'Exported',
    share: 'Share',
    // Auth
    login_title: 'Welcome Back',
    signup_title: 'Create Account',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    full_name: 'Full Name',
    login_btn: 'Login',
    signup_btn: 'Sign Up',
    no_account: "Don't have an account?",
    have_account: 'Already have an account?',
    enter_name: 'Enter your name',
    enter_email: 'Enter your email',
    enter_password: 'Enter your password',
    confirm_password_placeholder: 'Confirm your password',
    password_min: 'At least 8 characters',
    creating_account: 'Creating Account...',
    logging_in: 'Logging in...',
    login_subtitle: 'Login to manage your catalog',
    signup_subtitle: 'Start building your digital catalog',
    something_wrong: 'Something went wrong. Please try again.',
    // Dashboard
    share_catalog: 'Share Catalog',
    link_copied: 'Link Copied!',
    payment: 'Payment',
    delete_confirm: 'Are you sure you want to delete this product?',
    failed_load: 'Failed to load products. Please try again.',
    failed_delete: 'Failed to delete product. Please try again.',
    my_catalog_title: 'My Product Catalog',
    share_catalog_title: 'My Product Catalog',
    share_catalog_text: 'Check out my product catalog!',
    // Public Catalog
    catalog_not_found: 'Catalog Not Found',
    products_available: 'products available',
    share_catalog: 'Share Catalog',
    link_copied: 'Link Copied!',
    no_products_catalog: 'No products in this catalog yet.',
    tap_view_details: 'Tap to view details',
    product_details: 'Product Details',
    sold_by: 'Sold by',
    contact_whatsapp: 'Contact Seller on WhatsApp',
    whatsapp_note: 'Opens WhatsApp with a pre-filled message',
    payment_options: 'Payment Options',
    pay_via_upi: 'Pay via UPI',
    scan_to_pay: 'Scan to Pay',
    powered_by: 'Powered by Digital Catalog Agent',
    create_own_catalog: 'Create your own catalog at',
    // Voice Commands
    voice_help: 'Say: "go to dashboard", "add product", "export catalog", "logout"',
    command_recognized: 'Command recognized',
    command_not_recognized: 'Command not recognized. Try again.',
    // Payment Settings
    payment_title: 'Payment Settings',
    payment_subtitle: 'Add your payment details to receive payments from customers',
    upi: 'UPI',
    bank_account: 'Bank Account',
    qr_code: 'QR Code',
    upi_id: 'UPI ID',
    upi_name: 'Name on UPI',
    add_upi: 'Add Another UPI',
    account_name: 'Account Holder Name',
    account_number: 'Account Number',
    ifsc_code: 'IFSC Code',
    bank_name: 'Bank Name',
    upload_qr: 'Upload QR Code',
    save_payment: 'Save Payment Details',
    payment_saved: 'Payment details saved successfully!',
    remove: 'Remove',
    saving_text: 'Saving...',
    // Add/Edit Product
    add_new_product: 'Add New Product',
    edit_product: 'Edit Product',
    use_voice_text: 'Use voice or text to create your product listing',
    select_language: 'Select Your Language',
    describe_method: 'How would you like to describe your product?',
    voice: 'Voice',
    text: 'Text',
    speak_to_describe: 'Speak to describe',
    type_description: 'Type description',
    describe_product: 'Describe your product',
    describe_placeholder: 'E.g., "Handmade cotton saree with traditional block print design from Rajasthan..."',
    add_product_image: 'Add Product Image (optional)',
    upload: 'Upload',
    generate_with_ai: 'Generate Product Details with AI',
    ai_generating: 'AI is generating...',
    ai_generated_success: '✨ AI generated product listing! Review and edit below.',
    review_edit: 'Review & Edit Details',
    back_to_input: '← Back to Input',
    product_image: 'Product Image',
    product_name: 'Product Name',
    enter_product_name: 'Enter product name',
    description: 'Description',
    describe_your_product: 'Describe your product',
    category: 'Category',
    select_category: 'Select category',
    price: 'Price',
    enter_price: 'Enter price',
    language: 'Language',
    cancel: 'Cancel',
    add_to_catalog: '✓ Add Product to Catalog',
    adding_product: 'Adding Product...',
    save_changes: 'Save Changes',
    tip_describe: '💡 Tip: Describe your product in detail for better AI-generated listings',
    supports_voice: 'Supports voice input in Hindi, Tamil, Telugu, Kannada, and Bengali',
    step_describe: 'Describe',
    step_review: 'Review & Save',
    please_describe: 'Please describe your product first using voice or text',
    failed_generate: 'Failed to generate product details. Please try again.',
    voice_commands: 'Voice Commands',
    voice_commands_desc: 'Click "Voice Update" and say:',
    voice_update: 'Voice Update',
    listening_text: 'Listening...',
    voice_example_price: '"Update price to 500" or "Price 200 rupees karo"',
    voice_example_category: '"Change category to clothing"',
    voice_example_name: '"Name badlo Silk Saree"',
    voice_example_save: '"Save" or "Save changes" - saves and goes to dashboard',
    voice_example_cancel: '"Cancel" or "Go back" - goes back without saving',
    // Export
    export_platforms_title: 'Export to Seller Platforms',
    how_to_upload: 'How to Upload to Seller Platforms',
    step1_export: 'Export your catalog in the platform-specific format',
    step2_login: 'Log in to your seller account on the platform',
    step3_bulk: 'Go to "Bulk Upload" or "Import Products" section',
    step4_upload: 'Upload the exported file and review your listings',
    pro_tip: '💡 Pro tip: In future versions, we\'ll support direct API integration for one-click publishing!',
  },
  hi: {
    nav_home: 'होम',
    nav_dashboard: 'मेरी सूची',
    nav_demo: 'डेमो देखें',
    nav_login: 'लॉगिन',
    nav_signup: 'साइन अप',
    nav_logout: 'लॉगआउट',
    hero_title: 'स्थानीय विक्रेताओं के लिए AI-संचालित डिजिटल कैटलॉग',
    hero_subtitle: 'अपनी भाषा में आवाज़ का उपयोग करके पेशेवर उत्पाद सूची बनाएं',
    get_started: 'मुफ्त शुरू करें',
    try_demo: 'डेमो देखें',
    choose_language: 'अपनी भाषा चुनें',
    free_to_use: 'मुफ्त उपयोग',
    indian_languages: '6 भारतीय भाषाएं',
    ai_powered: 'AI-संचालित',
    accessibility_ready: 'सुलभता तैयार',
    voice_commands_enabled: 'वॉइस कमांड सक्षम',
    voice_commands_help: 'वॉइस कमांड सीखने के लिए "मदद" बोलें • दृष्टिबाधित उपयोगकर्ताओं के लिए सुलभ',
    powerful_features: 'छोटे व्यवसायों के लिए शक्तिशाली सुविधाएं',
    features_subtitle: 'बिना किसी तकनीकी ज्ञान के पेशेवर उत्पाद कैटलॉग बनाने के लिए आवश्यक सब कुछ',
    feature_voice_title: 'आवाज़ इनपुट',
    feature_voice_desc: 'अपने उत्पादों का वर्णन करने के लिए बस बोलें। हमारा AI हिंदी, तमिल, तेलुगु, कन्नड़, बंगाली और अंग्रेजी समझता है।',
    feature_photo_title: 'फोटो कैप्चर',
    feature_photo_desc: 'अपने उत्पाद की फोटो लें और AI को स्वचालित रूप से विवरण बनाने दें।',
    feature_ai_title: 'AI विवरण',
    feature_ai_desc: 'तुरंत पेशेवर उत्पाद विवरण, श्रेणियां और मूल्य सुझाव प्राप्त करें।',
    feature_multilang_title: 'बहु-भाषा',
    feature_multilang_desc: 'अपनी स्थानीय भाषा में कैटलॉग बनाएं। अधिक ग्राहकों तक पहुंचने के लिए स्वचालित अनुवाद।',
    feature_mobile_title: 'मोबाइल-फर्स्ट',
    feature_mobile_desc: 'स्मार्टफोन के लिए डिज़ाइन किया गया। बेसिक फोन और धीमे इंटरनेट के साथ भी आसान।',
    feature_share_title: 'कहीं भी साझा करें',
    feature_share_desc: 'ग्राहकों तक पहुंचने के लिए WhatsApp, Facebook या किसी भी प्लेटफॉर्म पर अपना कैटलॉग लिंक साझा करें।',
    challenges_title: 'हम जो चुनौतियां हल करते हैं',
    challenges_subtitle: 'छोटे व्यवसायों को डिजिटल होने में वास्तविक बाधाओं का सामना करना पड़ता है',
    challenge_skills_title: 'कम डिजिटल कौशल',
    challenge_skills_desc: 'कई दुकानदारों को तकनीक भ्रमित करने वाली लगती है। जटिल ऐप्स और फॉर्म भारी होते हैं।',
    challenge_skills_solution: 'हमारे वॉइस-फर्स्ट दृष्टिकोण को टाइपिंग या तकनीकी ज्ञान की आवश्यकता नहीं है।',
    challenge_language_title: 'भाषा बाधाएं',
    challenge_language_desc: 'अधिकांश डिजिटल टूल अंग्रेजी में हैं, जो स्थानीय भाषाओं को पसंद करने वाले लाखों लोगों को बाहर करते हैं।',
    challenge_language_solution: 'हिंदी, तमिल, तेलुगु, कन्नड़, बंगाली और अंग्रेजी के लिए पूर्ण समर्थन।',
    challenge_presence_title: 'कोई ऑनलाइन उपस्थिति नहीं',
    challenge_presence_desc: 'कैटलॉग के बिना, व्यवसाय ऑनलाइन नए ग्राहकों तक पहुंचने के अवसर खो देते हैं।',
    challenge_presence_solution: 'दिनों में नहीं, मिनटों में साझा करने योग्य कैटलॉग बनाएं।',
    how_it_works: 'यह कैसे काम करता है',
    how_it_works_subtitle: '2 मिनट से कम में अपनी पहली उत्पाद सूची बनाएं',
    step1_title: 'भाषा चुनें',
    step1_desc: '6 भारतीय भाषाओं में से अपनी पसंदीदा भाषा चुनें',
    step2_title: 'उत्पाद का वर्णन करें',
    step2_desc: 'बोलें, टाइप करें, या अपने उत्पाद की फोटो लें',
    step3_title: 'AI बनाता है',
    step3_desc: 'AI पेशेवर नाम, विवरण और श्रेणी बनाता है',
    step4_title: 'कैटलॉग साझा करें',
    step4_desc: 'ग्राहकों के साथ अपना कैटलॉग लिंक साझा करें',
    stat_languages: 'समर्थित भाषाएं',
    stat_inputs: 'इनपुट विधियां',
    stat_categories: 'उत्पाद श्रेणियां',
    stat_products: 'आप जोड़ सकते हैं उत्पाद',
    cta_title: 'अपने व्यवसाय को डिजिटल करने के लिए तैयार?',
    cta_subtitle: 'हजारों छोटे व्यवसायों से जुड़ें जो पहले से डिजिटल कैटलॉग एजेंट का उपयोग कर रहे हैं। यह मुफ्त, आसान है और आपकी भाषा में काम करता है।',
    cta_button: 'अभी अपना कैटलॉग बनाएं',
    cta_footer: 'डिजिटल इंडिया पहल का समर्थन • भारत के लिए बनाया गया 🇮🇳',
    my_catalog: 'मेरी सूची',
    products_count: 'उत्पाद',
    publish_platforms: 'प्लेटफॉर्म पर प्रकाशित करें',
    add_product: 'उत्पाद जोड़ें',
    no_products: 'अभी कोई उत्पाद नहीं है। अपना पहला उत्पाद जोड़कर शुरू करें!',
    add_first: 'अपना पहला उत्पाद जोड़ें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    deleting: 'हटा रहे हैं...',
    add_new_product: 'नया उत्पाद जोड़ें',
    product_name: 'उत्पाद का नाम',
    description: 'विवरण',
    category: 'श्रेणी',
    price: 'कीमत',
    language: 'भाषा',
    save_product: 'उत्पाद सहेजें',
    saving: 'सहेज रहे हैं...',
    select_language: 'अपनी भाषा चुनें',
    describe_method: 'आप अपने उत्पाद का वर्णन कैसे करना चाहेंगे?',
    voice: 'आवाज़',
    text: 'टेक्स्ट',
    camera: 'कैमरा',
    speak_to_describe: 'बोलकर बताएं',
    type_description: 'टाइप करें',
    take_a_photo: 'फोटो लें',
    describe_product: 'अपने उत्पाद का वर्णन करें',
    describe_placeholder: 'जैसे: "राजस्थान से पारंपरिक ब्लॉक प्रिंट डिज़ाइन वाली हस्तनिर्मित सूती साड़ी, त्योहारों के लिए बिल्कुल सही..."',
    add_description_photo: 'बेहतर AI परिणामों के लिए विवरण जोड़ें',
    describe_photo: 'फोटो में क्या है बताएं...',
    generate_with_ai: 'AI से उत्पाद विवरण बनाएं',
    ai_generating: 'AI बना रहा है...',
    ai_success: '✨ AI ने आपकी आवाज़ से अंग्रेज़ी उत्पाद सूची बनाई! नीचे देखें और संपादित करें।',
    review_edit: 'समीक्षा करें और संपादित करें',
    back_to_input: '← वापस जाएं',
    product_image: 'उत्पाद छवि',
    enter_product_name: 'उत्पाद का नाम दर्ज करें',
    describe_your_product: 'अपने उत्पाद का वर्णन करें',
    select_category: 'श्रेणी चुनें',
    enter_price: 'कीमत दर्ज करें',
    cancel: 'रद्द करें',
    add_to_catalog: '✓ कैटलॉग में जोड़ें',
    adding_product: 'उत्पाद जोड़ रहे हैं...',
    tip_describe: '💡 सुझाव: बेहतर AI सूची के लिए अपने उत्पाद का विस्तार से वर्णन करें',
    supports_voice: 'हिंदी, तमिल, तेलुगु, कन्नड़ और बंगाली में आवाज़ इनपुट समर्थित',
    step_describe: 'वर्णन करें',
    step_review: 'समीक्षा और सहेजें',
    please_describe: 'कृपया पहले आवाज़ या टेक्स्ट से अपने उत्पाद का वर्णन करें',
    failed_generate: 'उत्पाद विवरण बनाने में विफल। कृपया पुनः प्रयास करें।',
    voice_input: 'आवाज़ इनपुट',
    tap_to_speak: 'बोलने के लिए टैप करें',
    listening: 'सुन रहे हैं...',
    stop: 'रुकें',
    take_photo: 'फोटो लें',
    upload_image: 'छवि अपलोड करें',
    capture: 'कैप्चर',
    retake: 'फिर से लें',
    use_photo: 'फोटो उपयोग करें',
    publish_title: 'विक्रेता प्लेटफॉर्म पर प्रकाशित करें',
    publish_subtitle: 'अपनी सूची को प्रमुख ई-कॉमर्स प्लेटफॉर्म पर निर्यात करें',
    your_catalog: 'आपकी सूची',
    products_ready: 'उत्पाद प्रकाशित करने के लिए तैयार',
    view_products: 'उत्पाद देखें',
    share_link: 'साझा करने योग्य लिंक',
    share_link_desc: 'ग्राहकों के साथ यह लिंक साझा करें',
    copy: 'कॉपी',
    copied: 'कॉपी हो गया!',
    export: 'निर्यात',
    exporting: 'निर्यात हो रहा है...',
    exported: 'निर्यात हो गया',
    share: 'साझा करें',
    login_title: 'वापस स्वागत है',
    signup_title: 'खाता बनाएं',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirm_password: 'पासवर्ड की पुष्टि करें',
    login_btn: 'लॉगिन',
    signup_btn: 'साइन अप',
    no_account: 'खाता नहीं है?',
    have_account: 'पहले से खाता है?',
    // Public Catalog
    catalog_not_found: 'कैटलॉग नहीं मिला',
    products_available: 'उत्पाद उपलब्ध',
    share_catalog: 'कैटलॉग साझा करें',
    link_copied: 'लिंक कॉपी हो गया!',
    no_products_catalog: 'इस कैटलॉग में अभी कोई उत्पाद नहीं है।',
    tap_view_details: 'विवरण देखने के लिए टैप करें',
    product_details: 'उत्पाद विवरण',
    sold_by: 'विक्रेता',
    contact_whatsapp: 'WhatsApp पर विक्रेता से संपर्क करें',
    whatsapp_note: 'पहले से भरे संदेश के साथ WhatsApp खुलता है',
    payment_options: 'भुगतान विकल्प',
    pay_via_upi: 'UPI से भुगतान करें',
    scan_to_pay: 'भुगतान के लिए स्कैन करें',
    powered_by: 'डिजिटल कैटलॉग एजेंट द्वारा संचालित',
    create_own_catalog: 'अपना कैटलॉग बनाएं',
    voice_help: 'बोलें: "डैशबोर्ड जाओ", "उत्पाद जोड़ो", "निर्यात करो", "लॉगआउट"',
    command_recognized: 'आदेश पहचाना गया',
    command_not_recognized: 'आदेश नहीं पहचाना। फिर से कोशिश करें।',
    // Payment Settings
    payment_title: 'भुगतान सेटिंग्स',
    payment_subtitle: 'ग्राहकों से भुगतान प्राप्त करने के लिए अपना भुगतान विवरण जोड़ें',
    upi: 'यूपीआई',
    bank_account: 'बैंक खाता',
    qr_code: 'क्यूआर कोड',
    upi_id: 'यूपीआई आईडी',
    upi_name: 'यूपीआई पर नाम',
    add_upi: 'एक और यूपीआई जोड़ें',
    account_name: 'खाताधारक का नाम',
    account_number: 'खाता संख्या',
    ifsc_code: 'आईएफएससी कोड',
    bank_name: 'बैंक का नाम',
    upload_qr: 'क्यूआर कोड अपलोड करें',
    save_payment: 'भुगतान विवरण सहेजें',
    payment_saved: 'भुगतान विवरण सफलतापूर्वक सहेजा गया!',
    remove: 'हटाएं',
    saving_text: 'सहेज रहे हैं...',
    // Add/Edit Product
    add_new_product: 'नया उत्पाद जोड़ें',
    edit_product: 'उत्पाद संपादित करें',
    use_voice_text: 'अपनी उत्पाद सूची बनाने के लिए आवाज़ या टेक्स्ट का उपयोग करें',
    select_language: 'अपनी भाषा चुनें',
    describe_method: 'आप अपने उत्पाद का वर्णन कैसे करना चाहेंगे?',
    voice: 'आवाज़',
    text: 'टेक्स्ट',
    speak_to_describe: 'बोलकर बताएं',
    type_description: 'टाइप करें',
    describe_product: 'अपने उत्पाद का वर्णन करें',
    describe_placeholder: 'जैसे: "राजस्थान से पारंपरिक ब्लॉक प्रिंट डिज़ाइन वाली हस्तनिर्मित सूती साड़ी..."',
    add_product_image: 'उत्पाद छवि जोड़ें (वैकल्पिक)',
    upload: 'अपलोड',
    generate_with_ai: 'AI से उत्पाद विवरण बनाएं',
    ai_generating: 'AI बना रहा है...',
    ai_generated_success: '✨ AI ने उत्पाद सूची बनाई! नीचे देखें और संपादित करें।',
    review_edit: 'समीक्षा करें और संपादित करें',
    back_to_input: '← वापस जाएं',
    product_image: 'उत्पाद छवि',
    product_name: 'उत्पाद का नाम',
    enter_product_name: 'उत्पाद का नाम दर्ज करें',
    description: 'विवरण',
    describe_your_product: 'अपने उत्पाद का वर्णन करें',
    category: 'श्रेणी',
    select_category: 'श्रेणी चुनें',
    price: 'कीमत',
    enter_price: 'कीमत दर्ज करें',
    language: 'भाषा',
    cancel: 'रद्द करें',
    add_to_catalog: '✓ कैटलॉग में जोड़ें',
    adding_product: 'उत्पाद जोड़ रहे हैं...',
    save_changes: 'परिवर्तन सहेजें',
    tip_describe: '💡 सुझाव: बेहतर AI सूची के लिए अपने उत्पाद का विस्तार से वर्णन करें',
    supports_voice: 'हिंदी, तमिल, तेलुगु, कन्नड़ और बंगाली में आवाज़ इनपुट समर्थित',
    step_describe: 'वर्णन करें',
    step_review: 'समीक्षा और सहेजें',
    please_describe: 'कृपया पहले आवाज़ या टेक्स्ट से अपने उत्पाद का वर्णन करें',
    failed_generate: 'उत्पाद विवरण बनाने में विफल। कृपया पुनः प्रयास करें।',
    voice_commands: 'वॉइस कमांड',
    voice_commands_desc: '"वॉइस अपडेट" पर क्लिक करें और बोलें:',
    voice_update: 'वॉइस अपडेट',
    listening_text: 'सुन रहे हैं...',
    voice_example_price: '"कीमत 500 करो" या "Price 200 rupees"',
    voice_example_category: '"श्रेणी कपड़े करो"',
    voice_example_name: '"नाम सिल्क साड़ी करो"',
    voice_example_save: '"सेव करो" - सहेजें और डैशबोर्ड पर जाएं',
    voice_example_cancel: '"रद्द करो" या "वापस जाओ" - बिना सहेजे वापस जाएं',
    // Export
    export_platforms_title: 'विक्रेता प्लेटफॉर्म पर निर्यात करें',
    how_to_upload: 'विक्रेता प्लेटफॉर्म पर कैसे अपलोड करें',
    step1_export: 'प्लेटफॉर्म-विशिष्ट प्रारूप में अपनी सूची निर्यात करें',
    step2_login: 'प्लेटफॉर्म पर अपने विक्रेता खाते में लॉगिन करें',
    step3_bulk: '"बल्क अपलोड" या "उत्पाद आयात" अनुभाग पर जाएं',
    step4_upload: 'निर्यात की गई फ़ाइल अपलोड करें और अपनी सूची की समीक्षा करें',
    pro_tip: '💡 प्रो टिप: भविष्य के संस्करणों में, हम एक-क्लिक प्रकाशन के लिए सीधे API एकीकरण का समर्थन करेंगे!',
  },
  ta: {
    nav_home: 'முகப்பு',
    nav_dashboard: 'என் பட்டியல்',
    nav_demo: 'டெமோ',
    nav_login: 'உள்நுழை',
    nav_signup: 'பதிவு செய்',
    nav_logout: 'வெளியேறு',
    hero_title: 'AI டிஜிட்டல் கேட்டலாக்',
    hero_subtitle: 'உங்கள் மொழியில் குரல் மூலம் பொருட்களை பட்டியலிடுங்கள்',
    get_started: 'இலவசமாக தொடங்கு',
    try_demo: 'டெமோ பார்',
    choose_language: 'உங்கள் மொழியை தேர்வு செய்யவும்',
    free_to_use: 'இலவசம்',
    indian_languages: '6 இந்திய மொழிகள்',
    ai_powered: 'AI இயக்கம்',
    accessibility_ready: 'அணுகல் தயார்',
    voice_commands_enabled: 'குரல் கட்டளைகள் இயக்கப்பட்டது',
    voice_commands_help: 'குரல் கட்டளைகளை அறிய "உதவி" என்று சொல்லுங்கள் • பார்வை குறைபாடு உள்ளவர்களுக்கு அணுகக்கூடியது',
    powerful_features: 'சிறு வணிகங்களுக்கான சக்திவாய்ந்த அம்சங்கள்',
    features_subtitle: 'தொழில்நுட்ப அறிவு இல்லாமல் தொழில்முறை தயாரிப்பு பட்டியல்களை உருவாக்க தேவையான அனைத்தும்',
    feature_voice_title: 'குரல் உள்ளீடு',
    feature_voice_desc: 'உங்கள் பொருட்களை விவரிக்க பேசுங்கள். எங்கள் AI இந்தி, தமிழ், தெலுங்கு, கன்னடம், வங்காளம் மற்றும் ஆங்கிலம் புரிந்துகொள்கிறது.',
    feature_photo_title: 'புகைப்படம் எடுப்பு',
    feature_photo_desc: 'உங்கள் பொருளின் புகைப்படம் எடுங்கள், AI தானாகவே விவரத்தை உருவாக்கும்.',
    feature_ai_title: 'AI விவரங்கள்',
    feature_ai_desc: 'தொழில்முறை தயாரிப்பு விவரங்கள், வகைகள் மற்றும் விலை பரிந்துரைகளை உடனடியாக பெறுங்கள்.',
    feature_multilang_title: 'பல மொழி',
    feature_multilang_desc: 'உங்கள் உள்ளூர் மொழியில் பட்டியல்களை உருவாக்குங்கள். அதிக வாடிக்கையாளர்களை அடைய தானாக மொழிபெயர்க்கவும்.',
    feature_mobile_title: 'மொபைல்-முதல்',
    feature_mobile_desc: 'ஸ்மார்ட்போன்களுக்காக வடிவமைக்கப்பட்டது. அடிப்படை போன்கள் மற்றும் மெதுவான இணையத்திலும் எளிதாக பயன்படுத்தலாம்.',
    feature_share_title: 'எங்கும் பகிர்',
    feature_share_desc: 'வாடிக்கையாளர்களை அடைய WhatsApp, Facebook அல்லது எந்த தளத்திலும் உங்கள் பட்டியல் இணைப்பை பகிரவும்.',
    challenges_title: 'நாங்கள் தீர்க்கும் சவால்கள்',
    challenges_subtitle: 'சிறு வணிகங்கள் டிஜிட்டல் ஆவதில் உண்மையான தடைகளை எதிர்கொள்கின்றன',
    challenge_skills_title: 'குறைந்த டிஜிட்டல் திறன்கள்',
    challenge_skills_desc: 'பல கடைக்காரர்கள் தொழில்நுட்பத்தை குழப்பமாக காண்கிறார்கள். சிக்கலான ஆப்ஸ் மற்றும் படிவங்கள் அதிகமாக உள்ளன.',
    challenge_skills_solution: 'எங்கள் குரல்-முதல் அணுகுமுறைக்கு தட்டச்சு அல்லது தொழில்நுட்ப அறிவு தேவையில்லை.',
    challenge_language_title: 'மொழி தடைகள்',
    challenge_language_desc: 'பெரும்பாலான டிஜிட்டல் கருவிகள் ஆங்கிலத்தில் உள்ளன, உள்ளூர் மொழிகளை விரும்பும் மில்லியன் கணக்கானவர்களை விலக்குகின்றன.',
    challenge_language_solution: 'இந்தி, தமிழ், தெலுங்கு, கன்னடம், வங்காளம் மற்றும் ஆங்கிலத்திற்கு முழு ஆதரவு.',
    challenge_presence_title: 'ஆன்லைன் இருப்பு இல்லை',
    challenge_presence_desc: 'பட்டியல் இல்லாமல், வணிகங்கள் புதிய வாடிக்கையாளர்களை ஆன்லைனில் அடையும் வாய்ப்புகளை இழக்கின்றன.',
    challenge_presence_solution: 'நாட்கள் அல்ல, நிமிடங்களில் பகிரக்கூடிய பட்டியல்களை உருவாக்குங்கள்.',
    how_it_works: 'இது எப்படி வேலை செய்கிறது',
    how_it_works_subtitle: '2 நிமிடங்களுக்குள் உங்கள் முதல் தயாரிப்பு பட்டியலை உருவாக்குங்கள்',
    step1_title: 'மொழி தேர்வு',
    step1_desc: '6 இந்திய மொழிகளில் இருந்து உங்கள் விருப்பமான மொழியை தேர்வு செய்யவும்',
    step2_title: 'பொருளை விவரி',
    step2_desc: 'பேசுங்கள், தட்டச்சு செய்யுங்கள் அல்லது உங்கள் பொருளின் புகைப்படம் எடுங்கள்',
    step3_title: 'AI உருவாக்குகிறது',
    step3_desc: 'AI தொழில்முறை பெயர், விவரம் & வகையை உருவாக்குகிறது',
    step4_title: 'பட்டியலை பகிர்',
    step4_desc: 'வாடிக்கையாளர்களுடன் உங்கள் பட்டியல் இணைப்பை பகிரவும்',
    stat_languages: 'ஆதரிக்கப்படும் மொழிகள்',
    stat_inputs: 'உள்ளீட்டு முறைகள்',
    stat_categories: 'தயாரிப்பு வகைகள்',
    stat_products: 'நீங்கள் சேர்க்கக்கூடிய பொருட்கள்',
    cta_title: 'உங்கள் வணிகத்தை டிஜிட்டல் ஆக்க தயாரா?',
    cta_subtitle: 'ஏற்கனவே டிஜிட்டல் கேட்டலாக் ஏஜென்ட் பயன்படுத்தும் ஆயிரக்கணக்கான சிறு வணிகங்களுடன் சேருங்கள். இது இலவசம், எளிதானது மற்றும் உங்கள் மொழியில் வேலை செய்கிறது.',
    cta_button: 'இப்போது உங்கள் பட்டியலை உருவாக்குங்கள்',
    cta_footer: 'டிஜிட்டல் இந்தியா முன்முயற்சியை ஆதரிக்கிறது • பாரதத்திற்காக உருவாக்கப்பட்டது 🇮🇳',
    my_catalog: 'என் பட்டியல்',
    products_count: 'பொருட்கள்',
    publish_platforms: 'தளங்களில் வெளியிடு',
    add_product: 'பொருள் சேர்',
    no_products: 'இன்னும் பொருட்கள் இல்லை. முதல் பொருளை சேர்க்கவும்!',
    add_first: 'முதல் பொருளை சேர்',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    deleting: 'நீக்குகிறது...',
    add_new_product: 'புதிய பொருள் சேர்',
    product_name: 'பொருள் பெயர்',
    description: 'விவரம்',
    category: 'வகை',
    price: 'விலை',
    language: 'மொழி',
    save_product: 'பொருளை சேமி',
    saving: 'சேமிக்கிறது...',
    select_language: 'உங்கள் மொழியை தேர்வு செய்யவும்',
    describe_method: 'உங்கள் பொருளை எப்படி விவரிக்க விரும்புகிறீர்கள்?',
    voice: 'குரல்',
    text: 'உரை',
    camera: 'கேமரா',
    speak_to_describe: 'விவரிக்க பேசுங்கள்',
    type_description: 'விவரத்தை தட்டச்சு செய்யவும்',
    take_a_photo: 'புகைப்படம் எடுங்கள்',
    describe_product: 'உங்கள் பொருளை விவரிக்கவும்',
    describe_placeholder: 'எ.கா., "ராஜஸ்தானில் இருந்து பாரம்பரிய பிளாக் பிரிண்ட் டிசைன் கொண்ட கைவினை பருத்தி புடவை, பண்டிகைகளுக்கு சிறந்தது..."',
    add_description_photo: 'சிறந்த AI முடிவுகளுக்கு விவரத்தை சேர்க்கவும்',
    describe_photo: 'புகைப்படத்தில் என்ன இருக்கிறது என்று விவரிக்கவும்...',
    generate_with_ai: 'AI மூலம் பொருள் விவரங்களை உருவாக்கு',
    ai_generating: 'AI உருவாக்குகிறது...',
    ai_success: '✨ AI உங்கள் குரல் உள்ளீட்டிலிருந்து ஆங்கில பொருள் பட்டியலை உருவாக்கியது! கீழே மதிப்பாய்வு செய்து திருத்தவும்.',
    review_edit: 'மதிப்பாய்வு & திருத்து',
    back_to_input: '← உள்ளீட்டுக்கு திரும்பு',
    product_image: 'பொருள் படம்',
    enter_product_name: 'பொருள் பெயரை உள்ளிடவும்',
    describe_your_product: 'உங்கள் பொருளை விவரிக்கவும்',
    select_category: 'வகையை தேர்வு செய்யவும்',
    enter_price: 'விலையை உள்ளிடவும்',
    cancel: 'ரத்து செய்',
    add_to_catalog: '✓ கேட்டலாக்கில் சேர்',
    adding_product: 'பொருளை சேர்க்கிறது...',
    tip_describe: '💡 குறிப்பு: சிறந்த AI பட்டியல்களுக்கு உங்கள் பொருளை விரிவாக விவரிக்கவும்',
    supports_voice: 'இந்தி, தமிழ், தெலுங்கு, கன்னடம் மற்றும் வங்காளத்தில் குரல் உள்ளீடு ஆதரிக்கப்படுகிறது',
    step_describe: 'விவரி',
    step_review: 'மதிப்பாய்வு & சேமி',
    please_describe: 'முதலில் குரல் அல்லது உரை மூலம் உங்கள் பொருளை விவரிக்கவும்',
    failed_generate: 'பொருள் விவரங்களை உருவாக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    voice_input: 'குரல் உள்ளீடு',
    tap_to_speak: 'பேச தட்டவும்',
    listening: 'கேட்கிறது...',
    stop: 'நிறுத்து',
    take_photo: 'புகைப்படம் எடு',
    upload_image: 'படம் பதிவேற்று',
    capture: 'பிடி',
    retake: 'மீண்டும் எடு',
    use_photo: 'படத்தை பயன்படுத்து',
    publish_title: 'விற்பனை தளங்களில் வெளியிடு',
    publish_subtitle: 'உங்கள் பட்டியலை ஈ-காமர்ஸ் தளங்களுக்கு ஏற்றுமதி செய்யுங்கள்',
    your_catalog: 'உங்கள் பட்டியல்',
    products_ready: 'பொருட்கள் வெளியிட தயார்',
    view_products: 'பொருட்களை பார்',
    share_link: 'பகிரக்கூடிய இணைப்பு',
    share_link_desc: 'வாடிக்கையாளர்களுடன் இந்த இணைப்பை பகிரவும்',
    copy: 'நகலெடு',
    copied: 'நகலெடுக்கப்பட்டது!',
    export: 'ஏற்றுமதி',
    exporting: 'ஏற்றுமதி செய்கிறது...',
    exported: 'ஏற்றுமதி செய்யப்பட்டது',
    share: 'பகிர்',
    login_title: 'மீண்டும் வரவேற்கிறோம்',
    signup_title: 'கணக்கு உருவாக்கு',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    confirm_password: 'கடவுச்சொல்லை உறுதிப்படுத்து',
    full_name: 'முழு பெயர்',
    login_btn: 'உள்நுழை',
    signup_btn: 'பதிவு செய்',
    no_account: 'கணக்கு இல்லையா?',
    have_account: 'ஏற்கனவே கணக்கு உள்ளதா?',
    enter_name: 'உங்கள் பெயரை உள்ளிடவும்',
    enter_email: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    enter_password: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    confirm_password_placeholder: 'உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    password_min: 'குறைந்தது 8 எழுத்துகள்',
    creating_account: 'கணக்கு உருவாக்குகிறது...',
    logging_in: 'உள்நுழைகிறது...',
    login_subtitle: 'உங்கள் பட்டியலை நிர்வகிக்க உள்நுழையவும்',
    signup_subtitle: 'உங்கள் டிஜிட்டல் பட்டியலை உருவாக்க தொடங்குங்கள்',
    something_wrong: 'ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.',
    share_catalog: 'பட்டியலை பகிர்',
    link_copied: 'இணைப்பு நகலெடுக்கப்பட்டது!',
    payment: 'பணம்',
    delete_confirm: 'இந்த பொருளை நீக்க விரும்புகிறீர்களா?',
    failed_load: 'பொருட்களை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    failed_delete: 'பொருளை நீக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    my_catalog_title: 'என் பொருள் பட்டியல்',
    share_catalog_title: 'என் பொருள் பட்டியல்',
    share_catalog_text: 'என் பொருள் பட்டியலை பாருங்கள்!',
    // Public Catalog
    catalog_not_found: 'கேட்டலாக் கிடைக்கவில்லை',
    products_available: 'பொருட்கள் கிடைக்கும்',
    share_catalog: 'கேட்டலாக் பகிர்',
    link_copied: 'இணைப்பு நகலெடுக்கப்பட்டது!',
    no_products_catalog: 'இந்த கேட்டலாக்கில் இன்னும் பொருட்கள் இல்லை.',
    tap_view_details: 'விவரங்களைப் பார்க்க தட்டவும்',
    product_details: 'பொருள் விவரங்கள்',
    sold_by: 'விற்பனையாளர்',
    contact_whatsapp: 'WhatsApp-ல் விற்பனையாளரைத் தொடர்பு கொள்ளுங்கள்',
    whatsapp_note: 'முன்பே நிரப்பப்பட்ட செய்தியுடன் WhatsApp திறக்கும்',
    payment_options: 'பணம் செலுத்தும் விருப்பங்கள்',
    pay_via_upi: 'UPI மூலம் பணம் செலுத்துங்கள்',
    scan_to_pay: 'பணம் செலுத்த ஸ்கேன் செய்யுங்கள்',
    powered_by: 'டிஜிட்டல் கேட்டலாக் ஏஜென்ட் மூலம் இயக்கப்படுகிறது',
    create_own_catalog: 'உங்கள் சொந்த கேட்டலாக்கை உருவாக்குங்கள்',
    voice_help: 'சொல்லுங்கள்: "டாஷ்போர்டு போ", "பொருள் சேர்", "ஏற்றுமதி செய்", "வெளியேறு"',
    command_recognized: 'கட்டளை அங்கீகரிக்கப்பட்டது',
    command_not_recognized: 'கட்டளை புரியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    // Payment Settings
    payment_title: 'பணம் செலுத்தும் அமைப்புகள்',
    payment_subtitle: 'வாடிக்கையாளர்களிடமிருந்து பணம் பெற உங்கள் பணம் செலுத்தும் விவரங்களைச் சேர்க்கவும்',
    upi: 'யுபிஐ',
    bank_account: 'வங்கி கணக்கு',
    qr_code: 'கியூஆர் குறியீடு',
    upi_id: 'யுபிஐ ஐடி',
    upi_name: 'யுபிஐயில் பெயர்',
    add_upi: 'மற்றொரு யுபிஐ சேர்',
    account_name: 'கணக்கு வைத்திருப்பவர் பெயர்',
    account_number: 'கணக்கு எண்',
    ifsc_code: 'ஐஎஃப்எஸ்சி குறியீடு',
    bank_name: 'வங்கி பெயர்',
    upload_qr: 'கியூஆர் குறியீடு பதிவேற்று',
    save_payment: 'பணம் செலுத்தும் விவரங்களை சேமி',
    payment_saved: 'பணம் செலுத்தும் விவரங்கள் வெற்றிகரமாக சேமிக்கப்பட்டன!',
    remove: 'நீக்கு',
    saving_text: 'சேமிக்கிறது...',
    // Add/Edit Product
    add_new_product: 'புதிய பொருள் சேர்',
    edit_product: 'பொருளை திருத்து',
    use_voice_text: 'உங்கள் பொருள் பட்டியலை உருவாக்க குரல் அல்லது உரையைப் பயன்படுத்துங்கள்',
    select_language: 'உங்கள் மொழியை தேர்வு செய்யவும்',
    describe_method: 'உங்கள் பொருளை எப்படி விவரிக்க விரும்புகிறீர்கள்?',
    voice: 'குரல்',
    text: 'உரை',
    speak_to_describe: 'விவரிக்க பேசுங்கள்',
    type_description: 'விவரத்தை தட்டச்சு செய்யவும்',
    describe_product: 'உங்கள் பொருளை விவரிக்கவும்',
    describe_placeholder: 'எ.கா., "ராஜஸ்தானில் இருந்து பாரம்பரிய பிளாக் பிரிண்ட் டிசைன் கொண்ட கைவினை பருத்தி புடவை..."',
    add_product_image: 'பொருள் படம் சேர் (விருப்பமானது)',
    upload: 'பதிவேற்று',
    generate_with_ai: 'AI மூலம் பொருள் விவரங்களை உருவாக்கு',
    ai_generating: 'AI உருவாக்குகிறது...',
    ai_generated_success: '✨ AI பொருள் பட்டியலை உருவாக்கியது! கீழே மதிப்பாய்வு செய்து திருத்தவும்.',
    review_edit: 'மதிப்பாய்வு & திருத்து',
    back_to_input: '← உள்ளீட்டுக்கு திரும்பு',
    product_image: 'பொருள் படம்',
    product_name: 'பொருள் பெயர்',
    enter_product_name: 'பொருள் பெயரை உள்ளிடவும்',
    description: 'விவரம்',
    describe_your_product: 'உங்கள் பொருளை விவரிக்கவும்',
    category: 'வகை',
    select_category: 'வகையை தேர்வு செய்யவும்',
    price: 'விலை',
    enter_price: 'விலையை உள்ளிடவும்',
    language: 'மொழி',
    cancel: 'ரத்து செய்',
    add_to_catalog: '✓ கேட்டலாக்கில் சேர்',
    adding_product: 'பொருளை சேர்க்கிறது...',
    save_changes: 'மாற்றங்களை சேமி',
    tip_describe: '💡 குறிப்பு: சிறந்த AI பட்டியல்களுக்கு உங்கள் பொருளை விரிவாக விவரிக்கவும்',
    supports_voice: 'இந்தி, தமிழ், தெலுங்கு, கன்னடம் மற்றும் வங்காளத்தில் குரல் உள்ளீடு ஆதரிக்கப்படுகிறது',
    step_describe: 'விவரி',
    step_review: 'மதிப்பாய்வு & சேமி',
    please_describe: 'முதலில் குரல் அல்லது உரை மூலம் உங்கள் பொருளை விவரிக்கவும்',
    failed_generate: 'பொருள் விவரங்களை உருவாக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    voice_commands: 'குரல் கட்டளைகள்',
    voice_commands_desc: '"குரல் புதுப்பிப்பு" கிளிக் செய்து சொல்லுங்கள்:',
    voice_update: 'குரல் புதுப்பிப்பு',
    listening_text: 'கேட்கிறது...',
    voice_example_price: '"விலை 500 ஆக மாற்று"',
    voice_example_category: '"வகை ஆடை ஆக மாற்று"',
    voice_example_name: '"பெயர் சில்க் புடவை ஆக மாற்று"',
    voice_example_save: '"சேமி" - சேமித்து டாஷ்போர்டுக்கு செல்',
    voice_example_cancel: '"ரத்து செய்" அல்லது "திரும்பு" - சேமிக்காமல் திரும்பு',
    // Export
    export_platforms_title: 'விற்பனை தளங்களுக்கு ஏற்றுமதி செய்',
    how_to_upload: 'விற்பனை தளங்களில் எப்படி பதிவேற்றுவது',
    step1_export: 'தளம்-குறிப்பிட்ட வடிவத்தில் உங்கள் பட்டியலை ஏற்றுமதி செய்யுங்கள்',
    step2_login: 'தளத்தில் உங்கள் விற்பனையாளர் கணக்கில் உள்நுழையுங்கள்',
    step3_bulk: '"மொத்த பதிவேற்றம்" அல்லது "பொருட்களை இறக்குமதி" பகுதிக்கு செல்லுங்கள்',
    step4_upload: 'ஏற்றுமதி செய்த கோப்பை பதிவேற்றி உங்கள் பட்டியல்களை மதிப்பாய்வு செய்யுங்கள்',
    pro_tip: '💡 ப்ரோ டிப்: எதிர்கால பதிப்புகளில், ஒரே கிளிக்கில் வெளியிட நேரடி API ஒருங்கிணைப்பை ஆதரிப்போம்!',
  },
  te: {
    nav_home: 'హోమ్',
    nav_dashboard: 'నా జాబితా',
    nav_demo: 'డెమో',
    nav_login: 'లాగిన్',
    nav_signup: 'సైన్ అప్',
    nav_logout: 'లాగౌట్',
    hero_title: 'స్థానిక విక్రేతల కోసం AI డిజిటల్ కేటలాగ్',
    hero_subtitle: 'మీ భాషలో వాయిస్ ఉపయోగించి ప్రొఫెషనల్ జాబితాలు సృష్టించండి',
    get_started: 'ఉచితంగా ప్రారంభించండి',
    try_demo: 'డెమో చూడండి',
    choose_language: 'మీ భాషను ఎంచుకోండి',
    free_to_use: 'ఉచితంగా వాడండి',
    indian_languages: '6 భారతీయ భాషలు',
    ai_powered: 'AI-ఆధారిత',
    accessibility_ready: 'యాక్సెసిబిలిటీ సిద్ధం',
    voice_commands_enabled: 'వాయిస్ కమాండ్లు ఎనేబుల్',
    voice_commands_help: 'వాయిస్ కమాండ్లు నేర్చుకోవడానికి "సహాయం" చెప్పండి • దృష్టి లోపం ఉన్నవారికి అందుబాటులో',
    powerful_features: 'చిన్న వ్యాపారాలకు శక్తివంతమైన ఫీచర్లు',
    features_subtitle: 'టెక్నికల్ నాలెడ్జ్ లేకుండా ప్రొఫెషనల్ ప్రొడక్ట్ కేటలాగ్‌లు సృష్టించడానికి అవసరమైనవన్నీ',
    feature_voice_title: 'వాయిస్ ఇన్‌పుట్',
    feature_voice_desc: 'మీ ఉత్పత్తులను వివరించడానికి మాట్లాడండి. మా AI హిందీ, తమిళం, తెలుగు, కన్నడ, బెంగాలీ మరియు ఇంగ్లీష్ అర్థం చేసుకుంటుంది.',
    feature_photo_title: 'ఫోటో క్యాప్చర్',
    feature_photo_desc: 'మీ ఉత్పత్తి ఫోటో తీయండి మరియు AI ఆటోమేటిక్‌గా వివరణ సృష్టిస్తుంది.',
    feature_ai_title: 'AI వివరణలు',
    feature_ai_desc: 'ప్రొఫెషనల్ ప్రొడక్ట్ వివరణలు, కేటగిరీలు మరియు ధర సూచనలు వెంటనే పొందండి.',
    feature_multilang_title: 'బహుళ-భాష',
    feature_multilang_desc: 'మీ స్థానిక భాషలో కేటలాగ్‌లు సృష్టించండి. ఎక్కువ కస్టమర్లను చేరుకోవడానికి ఆటో-ట్రాన్స్‌లేట్.',
    feature_mobile_title: 'మొబైల్-ఫస్ట్',
    feature_mobile_desc: 'స్మార్ట్‌ఫోన్‌ల కోసం డిజైన్ చేయబడింది. బేసిక్ ఫోన్లు మరియు స్లో ఇంటర్నెట్‌తో కూడా సులభం.',
    feature_share_title: 'ఎక్కడైనా షేర్ చేయండి',
    feature_share_desc: 'కస్టమర్లను చేరుకోవడానికి WhatsApp, Facebook లేదా ఏదైనా ప్లాట్‌ఫారమ్‌లో మీ కేటలాగ్ లింక్ షేర్ చేయండి.',
    challenges_title: 'మేము పరిష్కరించే సవాళ్లు',
    challenges_subtitle: 'చిన్న వ్యాపారాలు డిజిటల్ అవ్వడంలో నిజమైన అడ్డంకులను ఎదుర్కొంటాయి',
    challenge_skills_title: 'తక్కువ డిజిటల్ నైపుణ్యాలు',
    challenge_skills_desc: 'చాలా మంది షాప్‌కీపర్లకు టెక్నాలజీ గందరగోళంగా అనిపిస్తుంది. సంక్లిష్టమైన యాప్‌లు మరియు ఫారమ్‌లు భారంగా ఉంటాయి.',
    challenge_skills_solution: 'మా వాయిస్-ఫస్ట్ విధానానికి టైపింగ్ లేదా టెక్నికల్ నాలెడ్జ్ అవసరం లేదు.',
    challenge_language_title: 'భాషా అడ్డంకులు',
    challenge_language_desc: 'చాలా డిజిటల్ టూల్స్ ఇంగ్లీష్‌లో ఉన్నాయి, స్థానిక భాషలను ఇష్టపడే మిలియన్ల మందిని మినహాయిస్తాయి.',
    challenge_language_solution: 'హిందీ, తమిళం, తెలుగు, కన్నడ, బెంగాలీ మరియు ఇంగ్లీష్‌కు పూర్తి మద్దతు.',
    challenge_presence_title: 'ఆన్‌లైన్ ఉనికి లేదు',
    challenge_presence_desc: 'కేటలాగ్ లేకుండా, వ్యాపారాలు ఆన్‌లైన్‌లో కొత్త కస్టమర్లను చేరుకునే అవకాశాలను కోల్పోతాయి.',
    challenge_presence_solution: 'రోజులు కాదు, నిమిషాల్లో షేర్ చేయగల కేటలాగ్‌లు సృష్టించండి.',
    how_it_works: 'ఇది ఎలా పని చేస్తుంది',
    how_it_works_subtitle: '2 నిమిషాల్లోపు మీ మొదటి ప్రొడక్ట్ లిస్టింగ్ సృష్టించండి',
    step1_title: 'భాష ఎంచుకోండి',
    step1_desc: '6 భారతీయ భాషల నుండి మీకు ఇష్టమైన భాషను ఎంచుకోండి',
    step2_title: 'ఉత్పత్తిని వివరించండి',
    step2_desc: 'మాట్లాడండి, టైప్ చేయండి లేదా మీ ఉత్పత్తి ఫోటో తీయండి',
    step3_title: 'AI సృష్టిస్తుంది',
    step3_desc: 'AI ప్రొఫెషనల్ పేరు, వివరణ & కేటగిరీ సృష్టిస్తుంది',
    step4_title: 'కేటలాగ్ షేర్ చేయండి',
    step4_desc: 'కస్టమర్లతో మీ కేటలాగ్ లింక్ షేర్ చేయండి',
    stat_languages: 'మద్దతు ఉన్న భాషలు',
    stat_inputs: 'ఇన్‌పుట్ పద్ధతులు',
    stat_categories: 'ప్రొడక్ట్ కేటగిరీలు',
    stat_products: 'మీరు జోడించగల ఉత్పత్తులు',
    cta_title: 'మీ వ్యాపారాన్ని డిజిటల్ చేయడానికి సిద్ధంగా ఉన్నారా?',
    cta_subtitle: 'ఇప్పటికే డిజిటల్ కేటలాగ్ ఏజెంట్ ఉపయోగిస్తున్న వేలాది చిన్న వ్యాపారాలతో చేరండి. ఇది ఉచితం, సులభం మరియు మీ భాషలో పని చేస్తుంది.',
    cta_button: 'ఇప్పుడు మీ కేటలాగ్ సృష్టించండి',
    cta_footer: 'డిజిటల్ ఇండియా చొరవకు మద్దతు • భారత్ కోసం తయారు చేయబడింది 🇮🇳',
    my_catalog: 'నా జాబితా',
    products_count: 'ఉత్పత్తులు',
    publish_platforms: 'ప్లాట్‌ఫారమ్‌లలో ప్రచురించండి',
    add_product: 'ఉత్పత్తి జోడించు',
    no_products: 'ఇంకా ఉత్పత్తులు లేవు. మీ మొదటి ఉత్పత్తిని జోడించండి!',
    add_first: 'మొదటి ఉత్పత్తి జోడించు',
    edit: 'సవరించు',
    delete: 'తొలగించు',
    deleting: 'తొలగిస్తోంది...',
    add_new_product: 'కొత్త ఉత్పత్తి జోడించు',
    product_name: 'ఉత్పత్తి పేరు',
    description: 'వివరణ',
    category: 'వర్గం',
    price: 'ధర',
    language: 'భాష',
    save_product: 'ఉత్పత్తి సేవ్ చేయి',
    saving: 'సేవ్ చేస్తోంది...',
    voice_input: 'వాయిస్ ఇన్‌పుట్',
    tap_to_speak: 'మాట్లాడటానికి నొక్కండి',
    listening: 'వింటోంది...',
    stop: 'ఆపు',
    take_photo: 'ఫోటో తీయండి',
    upload_image: 'చిత్రం అప్‌లోడ్ చేయండి',
    capture: 'క్యాప్చర్',
    retake: 'మళ్ళీ తీయండి',
    use_photo: 'ఫోటో ఉపయోగించు',
    publish_title: 'విక్రేత ప్లాట్‌ఫారమ్‌లలో ప్రచురించండి',
    publish_subtitle: 'మీ కేటలాగ్‌ను ఈ-కామర్స్ ప్లాట్‌ఫారమ్‌లకు ఎగుమతి చేయండి',
    your_catalog: 'మీ కేటలాగ్',
    products_ready: 'ఉత్పత్తులు ప్రచురించడానికి సిద్ధంగా ఉన్నాయి',
    view_products: 'ఉత్పత్తులు చూడండి',
    share_link: 'షేర్ చేయగల లింక్',
    share_link_desc: 'కస్టమర్లతో ఈ లింక్ షేర్ చేయండి',
    copy: 'కాపీ',
    copied: 'కాపీ అయింది!',
    export: 'ఎగుమతి',
    exporting: 'ఎగుమతి చేస్తోంది...',
    exported: 'ఎగుమతి అయింది',
    share: 'షేర్',
    login_title: 'తిరిగి స్వాగతం',
    signup_title: 'ఖాతా సృష్టించండి',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    confirm_password: 'పాస్‌వర్డ్ నిర్ధారించండి',
    login_btn: 'లాగిన్',
    signup_btn: 'సైన్ అప్',
    no_account: 'ఖాతా లేదా?',
    have_account: 'ఇప్పటికే ఖాతా ఉందా?',
    // Public Catalog
    catalog_not_found: 'కేటలాగ్ కనుగొనబడలేదు',
    products_available: 'ఉత్పత్తులు అందుబాటులో ఉన్నాయి',
    share_catalog: 'కేటలాగ్ షేర్ చేయండి',
    link_copied: 'లింక్ కాపీ అయింది!',
    no_products_catalog: 'ఈ కేటలాగ్‌లో ఇంకా ఉత్పత్తులు లేవు.',
    tap_view_details: 'వివరాలు చూడటానికి నొక్కండి',
    product_details: 'ఉత్పత్తి వివరాలు',
    sold_by: 'విక్రేత',
    contact_whatsapp: 'WhatsAppలో విక్రేతను సంప్రదించండి',
    whatsapp_note: 'ముందుగా నింపిన సందేశంతో WhatsApp తెరుచుకుంటుంది',
    payment_options: 'చెల్లింపు ఎంపికలు',
    pay_via_upi: 'UPI ద్వారా చెల్లించండి',
    scan_to_pay: 'చెల్లించడానికి స్కాన్ చేయండి',
    powered_by: 'డిజిటల్ కేటలాగ్ ఏజెంట్ ద్వారా నడుపబడుతోంది',
    create_own_catalog: 'మీ స్వంత కేటలాగ్ సృష్టించండి',
    voice_help: 'చెప్పండి: "డాష్‌బోర్డ్ వెళ్ళు", "ఉత్పత్తి జోడించు", "ఎగుమతి చేయి", "లాగౌట్"',
    command_recognized: 'ఆదేశం గుర్తించబడింది',
    command_not_recognized: 'ఆదేశం గుర్తించలేదు. మళ్ళీ ప్రయత్నించండి.',
    // Payment Settings
    payment_title: 'చెల్లింపు సెట్టింగ్‌లు',
    payment_subtitle: 'కస్టమర్ల నుండి చెల్లింపులు పొందడానికి మీ చెల్లింపు వివరాలను జోడించండి',
    upi: 'యుపిఐ',
    bank_account: 'బ్యాంక్ ఖాతా',
    qr_code: 'క్యూఆర్ కోడ్',
    upi_id: 'యుపిఐ ఐడి',
    upi_name: 'యుపిఐలో పేరు',
    add_upi: 'మరొక యుపిఐ జోడించు',
    account_name: 'ఖాతాదారు పేరు',
    account_number: 'ఖాతా నంబర్',
    ifsc_code: 'ఐఎఫ్‌ఎస్‌సి కోడ్',
    bank_name: 'బ్యాంక్ పేరు',
    upload_qr: 'క్యూఆర్ కోడ్ అప్‌లోడ్ చేయండి',
    save_payment: 'చెల్లింపు వివరాలను సేవ్ చేయండి',
    payment_saved: 'చెల్లింపు వివరాలు విజయవంతంగా సేవ్ చేయబడ్డాయి!',
    remove: 'తొలగించు',
    saving_text: 'సేవ్ చేస్తోంది...',
    // Add/Edit Product
    add_new_product: 'కొత్త ఉత్పత్తి జోడించు',
    edit_product: 'ఉత్పత్తిని సవరించు',
    use_voice_text: 'మీ ఉత్పత్తి జాబితాను సృష్టించడానికి వాయిస్ లేదా టెక్స్ట్ ఉపయోగించండి',
    select_language: 'మీ భాషను ఎంచుకోండి',
    describe_method: 'మీ ఉత్పత్తిని ఎలా వివరించాలనుకుంటున్నారు?',
    voice: 'వాయిస్',
    text: 'టెక్స్ట్',
    speak_to_describe: 'వివరించడానికి మాట్లాడండి',
    type_description: 'వివరణ టైప్ చేయండి',
    describe_product: 'మీ ఉత్పత్తిని వివరించండి',
    describe_placeholder: 'ఉదా., "రాజస్థాన్ నుండి సాంప్రదాయ బ్లాక్ ప్రింట్ డిజైన్‌తో చేతితో తయారు చేసిన పత్తి చీర..."',
    add_product_image: 'ఉత్పత్తి చిత్రం జోడించండి (ఐచ్ఛికం)',
    upload: 'అప్‌లోడ్',
    generate_with_ai: 'AI తో ఉత్పత్తి వివరాలు సృష్టించండి',
    ai_generating: 'AI సృష్టిస్తోంది...',
    ai_generated_success: '✨ AI ఉత్పత్తి జాబితాను సృష్టించింది! కింద సమీక్షించి సవరించండి.',
    review_edit: 'సమీక్షించు & సవరించు',
    back_to_input: '← ఇన్‌పుట్‌కు తిరిగి వెళ్ళు',
    product_image: 'ఉత్పత్తి చిత్రం',
    product_name: 'ఉత్పత్తి పేరు',
    enter_product_name: 'ఉత్పత్తి పేరు నమోదు చేయండి',
    description: 'వివరణ',
    describe_your_product: 'మీ ఉత్పత్తిని వివరించండి',
    category: 'వర్గం',
    select_category: 'వర్గాన్ని ఎంచుకోండి',
    price: 'ధర',
    enter_price: 'ధర నమోదు చేయండి',
    language: 'భాష',
    cancel: 'రద్దు చేయి',
    add_to_catalog: '✓ కేటలాగ్‌కు జోడించు',
    adding_product: 'ఉత్పత్తిని జోడిస్తోంది...',
    save_changes: 'మార్పులను సేవ్ చేయి',
    tip_describe: '💡 చిట్కా: మెరుగైన AI జాబితాల కోసం మీ ఉత్పత్తిని వివరంగా వివరించండి',
    supports_voice: 'హిందీ, తమిళం, తెలుగు, కన్నడ మరియు బెంగాలీలో వాయిస్ ఇన్‌పుట్ మద్దతు',
    step_describe: 'వివరించు',
    step_review: 'సమీక్షించు & సేవ్ చేయి',
    please_describe: 'దయచేసి ముందుగా వాయిస్ లేదా టెక్స్ట్ ద్వారా మీ ఉత్పత్తిని వివరించండి',
    failed_generate: 'ఉత్పత్తి వివరాలను సృష్టించడం విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    voice_commands: 'వాయిస్ కమాండ్లు',
    voice_commands_desc: '"వాయిస్ అప్‌డేట్" క్లిక్ చేసి చెప్పండి:',
    voice_update: 'వాయిస్ అప్‌డేట్',
    listening_text: 'వింటోంది...',
    voice_example_price: '"ధర 500 కు మార్చు"',
    voice_example_category: '"వర్గం దుస్తులకు మార్చు"',
    voice_example_name: '"పేరు సిల్క్ చీరకు మార్చు"',
    voice_example_save: '"సేవ్ చేయి" - సేవ్ చేసి డాష్‌బోర్డ్‌కు వెళ్ళు',
    voice_example_cancel: '"రద్దు చేయి" లేదా "వెనక్కి వెళ్ళు" - సేవ్ చేయకుండా వెనక్కి వెళ్ళు',
    // Export
    export_platforms_title: 'విక్రేత ప్లాట్‌ఫారమ్‌లకు ఎగుమతి చేయండి',
    how_to_upload: 'విక్రేత ప్లాట్‌ఫారమ్‌లకు ఎలా అప్‌లోడ్ చేయాలి',
    step1_export: 'ప్లాట్‌ఫారమ్-నిర్దిష్ట ఫార్మాట్‌లో మీ కేటలాగ్‌ను ఎగుమతి చేయండి',
    step2_login: 'ప్లాట్‌ఫారమ్‌లో మీ విక్రేత ఖాతాలో లాగిన్ అవ్వండి',
    step3_bulk: '"బల్క్ అప్‌లోడ్" లేదా "ఉత్పత్తులను దిగుమతి చేయి" విభాగానికి వెళ్ళండి',
    step4_upload: 'ఎగుమతి చేసిన ఫైల్‌ను అప్‌లోడ్ చేసి మీ జాబితాలను సమీక్షించండి',
    pro_tip: '💡 ప్రో టిప్: భవిష్యత్ వెర్షన్లలో, ఒక-క్లిక్ ప్రచురణ కోసం డైరెక్ట్ API ఇంటిగ్రేషన్‌కు మద్దతు ఇస్తాము!',
  },
  kn: {
    nav_home: 'ಮುಖಪುಟ',
    nav_dashboard: 'ನನ್ನ ಪಟ್ಟಿ',
    nav_demo: 'ಡೆಮೊ',
    nav_login: 'ಲಾಗಿನ್',
    nav_signup: 'ಸೈನ್ ಅಪ್',
    nav_logout: 'ಲಾಗೌಟ್',
    hero_title: 'ಸ್ಥಳೀಯ ಮಾರಾಟಗಾರರಿಗೆ AI ಡಿಜಿಟಲ್ ಕ್ಯಾಟಲಾಗ್',
    hero_subtitle: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಧ್ವನಿ ಬಳಸಿ ವೃತ್ತಿಪರ ಪಟ್ಟಿಗಳನ್ನು ರಚಿಸಿ',
    get_started: 'ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
    try_demo: 'ಡೆಮೊ ನೋಡಿ',
    choose_language: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    free_to_use: 'ಉಚಿತವಾಗಿ ಬಳಸಿ',
    indian_languages: '6 ಭಾರತೀಯ ಭಾಷೆಗಳು',
    ai_powered: 'AI-ಚಾಲಿತ',
    accessibility_ready: 'ಪ್ರವೇಶಿಸುವಿಕೆ ಸಿದ್ಧ',
    voice_commands_enabled: 'ಧ್ವನಿ ಆದೇಶಗಳು ಸಕ್ರಿಯ',
    voice_commands_help: 'ಧ್ವನಿ ಆದೇಶಗಳನ್ನು ಕಲಿಯಲು "ಸಹಾಯ" ಎಂದು ಹೇಳಿ • ದೃಷ್ಟಿ ದೋಷವುಳ್ಳವರಿಗೆ ಪ್ರವೇಶಿಸಬಹುದು',
    powerful_features: 'ಸಣ್ಣ ವ್ಯಾಪಾರಗಳಿಗೆ ಶಕ್ತಿಶಾಲಿ ವೈಶಿಷ್ಟ್ಯಗಳು',
    features_subtitle: 'ತಾಂತ್ರಿಕ ಜ್ಞಾನವಿಲ್ಲದೆ ವೃತ್ತಿಪರ ಉತ್ಪನ್ನ ಕ್ಯಾಟಲಾಗ್‌ಗಳನ್ನು ರಚಿಸಲು ಅಗತ್ಯವಿರುವ ಎಲ್ಲವೂ',
    feature_voice_title: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
    feature_voice_desc: 'ನಿಮ್ಮ ಉತ್ಪನ್ನಗಳನ್ನು ವಿವರಿಸಲು ಮಾತನಾಡಿ. ನಮ್ಮ AI ಹಿಂದಿ, ತಮಿಳು, ತೆಲುಗು, ಕನ್ನಡ, ಬೆಂಗಾಲಿ ಮತ್ತು ಇಂಗ್ಲಿಷ್ ಅರ್ಥಮಾಡಿಕೊಳ್ಳುತ್ತದೆ.',
    feature_photo_title: 'ಫೋಟೋ ಕ್ಯಾಪ್ಚರ್',
    feature_photo_desc: 'ನಿಮ್ಮ ಉತ್ಪನ್ನದ ಫೋಟೋ ತೆಗೆಯಿರಿ ಮತ್ತು AI ಸ್ವಯಂಚಾಲಿತವಾಗಿ ವಿವರಣೆಯನ್ನು ರಚಿಸುತ್ತದೆ.',
    feature_ai_title: 'AI ವಿವರಣೆಗಳು',
    feature_ai_desc: 'ವೃತ್ತಿಪರ ಉತ್ಪನ್ನ ವಿವರಣೆಗಳು, ವರ್ಗಗಳು ಮತ್ತು ಬೆಲೆ ಸಲಹೆಗಳನ್ನು ತಕ್ಷಣ ಪಡೆಯಿರಿ.',
    feature_multilang_title: 'ಬಹು-ಭಾಷೆ',
    feature_multilang_desc: 'ನಿಮ್ಮ ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ಕ್ಯಾಟಲಾಗ್‌ಗಳನ್ನು ರಚಿಸಿ. ಹೆಚ್ಚು ಗ್ರಾಹಕರನ್ನು ತಲುಪಲು ಸ್ವಯಂ-ಅನುವಾದ.',
    feature_mobile_title: 'ಮೊಬೈಲ್-ಮೊದಲು',
    feature_mobile_desc: 'ಸ್ಮಾರ್ಟ್‌ಫೋನ್‌ಗಳಿಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ. ಮೂಲ ಫೋನ್‌ಗಳು ಮತ್ತು ನಿಧಾನ ಇಂಟರ್ನೆಟ್‌ನೊಂದಿಗೂ ಸುಲಭ.',
    feature_share_title: 'ಎಲ್ಲಿಯಾದರೂ ಹಂಚಿಕೊಳ್ಳಿ',
    feature_share_desc: 'ಗ್ರಾಹಕರನ್ನು ತಲುಪಲು WhatsApp, Facebook ಅಥವಾ ಯಾವುದೇ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಕ್ಯಾಟಲಾಗ್ ಲಿಂಕ್ ಹಂಚಿಕೊಳ್ಳಿ.',
    challenges_title: 'ನಾವು ಪರಿಹರಿಸುವ ಸವಾಲುಗಳು',
    challenges_subtitle: 'ಸಣ್ಣ ವ್ಯಾಪಾರಗಳು ಡಿಜಿಟಲ್ ಆಗುವಲ್ಲಿ ನಿಜವಾದ ಅಡೆತಡೆಗಳನ್ನು ಎದುರಿಸುತ್ತವೆ',
    challenge_skills_title: 'ಕಡಿಮೆ ಡಿಜಿಟಲ್ ಕೌಶಲ್ಯಗಳು',
    challenge_skills_desc: 'ಅನೇಕ ಅಂಗಡಿಕಾರರಿಗೆ ತಂತ್ರಜ್ಞಾನ ಗೊಂದಲಮಯವಾಗಿ ಕಾಣುತ್ತದೆ. ಸಂಕೀರ್ಣ ಅಪ್ಲಿಕೇಶನ್‌ಗಳು ಮತ್ತು ಫಾರ್ಮ್‌ಗಳು ಭಾರವಾಗಿರುತ್ತವೆ.',
    challenge_skills_solution: 'ನಮ್ಮ ಧ್ವನಿ-ಮೊದಲ ವಿಧಾನಕ್ಕೆ ಟೈಪಿಂಗ್ ಅಥವಾ ತಾಂತ್ರಿಕ ಜ್ಞಾನ ಅಗತ್ಯವಿಲ್ಲ.',
    challenge_language_title: 'ಭಾಷಾ ಅಡೆತಡೆಗಳು',
    challenge_language_desc: 'ಹೆಚ್ಚಿನ ಡಿಜಿಟಲ್ ಉಪಕರಣಗಳು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿವೆ, ಸ್ಥಳೀಯ ಭಾಷೆಗಳನ್ನು ಇಷ್ಟಪಡುವ ಲಕ್ಷಾಂತರ ಜನರನ್ನು ಹೊರಗಿಡುತ್ತವೆ.',
    challenge_language_solution: 'ಹಿಂದಿ, ತಮಿಳು, ತೆಲುಗು, ಕನ್ನಡ, ಬೆಂಗಾಲಿ ಮತ್ತು ಇಂಗ್ಲಿಷ್‌ಗೆ ಪೂರ್ಣ ಬೆಂಬಲ.',
    challenge_presence_title: 'ಆನ್‌ಲೈನ್ ಉಪಸ್ಥಿತಿ ಇಲ್ಲ',
    challenge_presence_desc: 'ಕ್ಯಾಟಲಾಗ್ ಇಲ್ಲದೆ, ವ್ಯಾಪಾರಗಳು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಹೊಸ ಗ್ರಾಹಕರನ್ನು ತಲುಪುವ ಅವಕಾಶಗಳನ್ನು ಕಳೆದುಕೊಳ್ಳುತ್ತವೆ.',
    challenge_presence_solution: 'ದಿನಗಳಲ್ಲ, ನಿಮಿಷಗಳಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಬಹುದಾದ ಕ್ಯಾಟಲಾಗ್‌ಗಳನ್ನು ರಚಿಸಿ.',
    how_it_works: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    how_it_works_subtitle: '2 ನಿಮಿಷಗಳಲ್ಲಿ ನಿಮ್ಮ ಮೊದಲ ಉತ್ಪನ್ನ ಪಟ್ಟಿಯನ್ನು ರಚಿಸಿ',
    step1_title: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    step1_desc: '6 ಭಾರತೀಯ ಭಾಷೆಗಳಿಂದ ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    step2_title: 'ಉತ್ಪನ್ನವನ್ನು ವಿವರಿಸಿ',
    step2_desc: 'ಮಾತನಾಡಿ, ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ನಿಮ್ಮ ಉತ್ಪನ್ನದ ಫೋಟೋ ತೆಗೆಯಿರಿ',
    step3_title: 'AI ರಚಿಸುತ್ತದೆ',
    step3_desc: 'AI ವೃತ್ತಿಪರ ಹೆಸರು, ವಿವರಣೆ & ವರ್ಗವನ್ನು ರಚಿಸುತ್ತದೆ',
    step4_title: 'ಕ್ಯಾಟಲಾಗ್ ಹಂಚಿಕೊಳ್ಳಿ',
    step4_desc: 'ಗ್ರಾಹಕರೊಂದಿಗೆ ನಿಮ್ಮ ಕ್ಯಾಟಲಾಗ್ ಲಿಂಕ್ ಹಂಚಿಕೊಳ್ಳಿ',
    stat_languages: 'ಬೆಂಬಲಿತ ಭಾಷೆಗಳು',
    stat_inputs: 'ಇನ್‌ಪುಟ್ ವಿಧಾನಗಳು',
    stat_categories: 'ಉತ್ಪನ್ನ ವರ್ಗಗಳು',
    stat_products: 'ನೀವು ಸೇರಿಸಬಹುದಾದ ಉತ್ಪನ್ನಗಳು',
    cta_title: 'ನಿಮ್ಮ ವ್ಯಾಪಾರವನ್ನು ಡಿಜಿಟಲ್ ಮಾಡಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
    cta_subtitle: 'ಈಗಾಗಲೇ ಡಿಜಿಟಲ್ ಕ್ಯಾಟಲಾಗ್ ಏಜೆಂಟ್ ಬಳಸುತ್ತಿರುವ ಸಾವಿರಾರು ಸಣ್ಣ ವ್ಯಾಪಾರಗಳೊಂದಿಗೆ ಸೇರಿ. ಇದು ಉಚಿತ, ಸುಲಭ ಮತ್ತು ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ.',
    cta_button: 'ಈಗ ನಿಮ್ಮ ಕ್ಯಾಟಲಾಗ್ ರಚಿಸಿ',
    cta_footer: 'ಡಿಜಿಟಲ್ ಇಂಡಿಯಾ ಉಪಕ್ರಮಕ್ಕೆ ಬೆಂಬಲ • ಭಾರತಕ್ಕಾಗಿ ತಯಾರಿಸಲಾಗಿದೆ 🇮🇳',
    my_catalog: 'ನನ್ನ ಪಟ್ಟಿ',
    products_count: 'ಉತ್ಪನ್ನಗಳು',
    publish_platforms: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗಳಲ್ಲಿ ಪ್ರಕಟಿಸಿ',
    add_product: 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    no_products: 'ಇನ್ನೂ ಉತ್ಪನ್ನಗಳಿಲ್ಲ. ನಿಮ್ಮ ಮೊದಲ ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ!',
    add_first: 'ಮೊದಲ ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    deleting: 'ಅಳಿಸುತ್ತಿದೆ...',
    add_new_product: 'ಹೊಸ ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    product_name: 'ಉತ್ಪನ್ನ ಹೆಸರು',
    description: 'ವಿವರಣೆ',
    category: 'ವರ್ಗ',
    price: 'ಬೆಲೆ',
    language: 'ಭಾಷೆ',
    save_product: 'ಉತ್ಪನ್ನ ಉಳಿಸಿ',
    saving: 'ಉಳಿಸುತ್ತಿದೆ...',
    voice_input: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
    tap_to_speak: 'ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    listening: 'ಕೇಳುತ್ತಿದೆ...',
    stop: 'ನಿಲ್ಲಿಸಿ',
    take_photo: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    upload_image: 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    capture: 'ಕ್ಯಾಪ್ಚರ್',
    retake: 'ಮತ್ತೆ ತೆಗೆಯಿರಿ',
    use_photo: 'ಫೋಟೋ ಬಳಸಿ',
    publish_title: 'ಮಾರಾಟ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗಳಲ್ಲಿ ಪ್ರಕಟಿಸಿ',
    publish_subtitle: 'ನಿಮ್ಮ ಕ್ಯಾಟಲಾಗ್ ಅನ್ನು ಇ-ಕಾಮರ್ಸ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗಳಿಗೆ ರಫ್ತು ಮಾಡಿ',
    your_catalog: 'ನಿಮ್ಮ ಕ್ಯಾಟಲಾಗ್',
    products_ready: 'ಉತ್ಪನ್ನಗಳು ಪ್ರಕಟಿಸಲು ಸಿದ್ಧ',
    view_products: 'ಉತ್ಪನ್ನಗಳನ್ನು ನೋಡಿ',
    share_link: 'ಹಂಚಿಕೊಳ್ಳಬಹುದಾದ ಲಿಂಕ್',
    share_link_desc: 'ಗ್ರಾಹಕರೊಂದಿಗೆ ಈ ಲಿಂಕ್ ಹಂಚಿಕೊಳ್ಳಿ',
    copy: 'ನಕಲಿಸಿ',
    copied: 'ನಕಲಿಸಲಾಗಿದೆ!',
    export: 'ರಫ್ತು',
    exporting: 'ರಫ್ತು ಮಾಡುತ್ತಿದೆ...',
    exported: 'ರಫ್ತು ಆಗಿದೆ',
    share: 'ಹಂಚಿಕೊಳ್ಳಿ',
    login_title: 'ಮರಳಿ ಸ್ವಾಗತ',
    signup_title: 'ಖಾತೆ ರಚಿಸಿ',
    email: 'ಇಮೇಲ್',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    confirm_password: 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    login_btn: 'ಲಾಗಿನ್',
    signup_btn: 'ಸೈನ್ ಅಪ್',
    no_account: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    have_account: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    // Public Catalog
    catalog_not_found: 'ಕ್ಯಾಟಲಾಗ್ ಕಂಡುಬಂದಿಲ್ಲ',
    products_available: 'ಉತ್ಪನ್ನಗಳು ಲಭ್ಯವಿದೆ',
    share_catalog: 'ಕ್ಯಾಟಲಾಗ್ ಹಂಚಿಕೊಳ್ಳಿ',
    link_copied: 'ಲಿಂಕ್ ನಕಲಿಸಲಾಗಿದೆ!',
    no_products_catalog: 'ಈ ಕ್ಯಾಟಲಾಗ್‌ನಲ್ಲಿ ಇನ್ನೂ ಉತ್ಪನ್ನಗಳಿಲ್ಲ.',
    tap_view_details: 'ವಿವರಗಳನ್ನು ನೋಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    product_details: 'ಉತ್ಪನ್ನ ವಿವರಗಳು',
    sold_by: 'ಮಾರಾಟಗಾರ',
    contact_whatsapp: 'WhatsAppನಲ್ಲಿ ಮಾರಾಟಗಾರರನ್ನು ಸಂಪರ್ಕಿಸಿ',
    whatsapp_note: 'ಮೊದಲೇ ತುಂಬಿದ ಸಂದೇಶದೊಂದಿಗೆ WhatsApp ತೆರೆಯುತ್ತದೆ',
    payment_options: 'ಪಾವತಿ ಆಯ್ಕೆಗಳು',
    pay_via_upi: 'UPI ಮೂಲಕ ಪಾವತಿಸಿ',
    scan_to_pay: 'ಪಾವತಿಸಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    powered_by: 'ಡಿಜಿಟಲ್ ಕ್ಯಾಟಲಾಗ್ ಏಜೆಂಟ್ ಮೂಲಕ ನಡೆಸಲಾಗುತ್ತಿದೆ',
    create_own_catalog: 'ನಿಮ್ಮ ಸ್ವಂತ ಕ್ಯಾಟಲಾಗ್ ರಚಿಸಿ',
    voice_help: 'ಹೇಳಿ: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಹೋಗು", "ಉತ್ಪನ್ನ ಸೇರಿಸು", "ರಫ್ತು ಮಾಡು", "ಲಾಗೌಟ್"',
    command_recognized: 'ಆದೇಶ ಗುರುತಿಸಲಾಗಿದೆ',
    command_not_recognized: 'ಆದೇಶ ಗುರುತಿಸಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    // Payment Settings
    payment_title: 'ಪಾವತಿ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    payment_subtitle: 'ಗ್ರಾಹಕರಿಂದ ಪಾವತಿಗಳನ್ನು ಸ್ವೀಕರಿಸಲು ನಿಮ್ಮ ಪಾವತಿ ವಿವರಗಳನ್ನು ಸೇರಿಸಿ',
    upi: 'ಯುಪಿಐ',
    bank_account: 'ಬ್ಯಾಂಕ್ ಖಾತೆ',
    qr_code: 'ಕ್ಯೂಆರ್ ಕೋಡ್',
    upi_id: 'ಯುಪಿಐ ಐಡಿ',
    upi_name: 'ಯುಪಿಐನಲ್ಲಿ ಹೆಸರು',
    add_upi: 'ಮತ್ತೊಂದು ಯುಪಿಐ ಸೇರಿಸಿ',
    account_name: 'ಖಾತೆದಾರರ ಹೆಸರು',
    account_number: 'ಖಾತೆ ಸಂಖ್ಯೆ',
    ifsc_code: 'ಐಎಫ್‌ಎಸ್‌ಸಿ ಕೋಡ್',
    bank_name: 'ಬ್ಯಾಂಕ್ ಹೆಸರು',
    upload_qr: 'ಕ್ಯೂಆರ್ ಕೋಡ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    save_payment: 'ಪಾವತಿ ವಿವರಗಳನ್ನು ಉಳಿಸಿ',
    payment_saved: 'ಪಾವತಿ ವಿವರಗಳು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!',
    remove: 'ತೆಗೆದುಹಾಕಿ',
    saving_text: 'ಉಳಿಸುತ್ತಿದೆ...',
    // Add/Edit Product
    add_new_product: 'ಹೊಸ ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    edit_product: 'ಉತ್ಪನ್ನವನ್ನು ಸಂಪಾದಿಸಿ',
    use_voice_text: 'ನಿಮ್ಮ ಉತ್ಪನ್ನ ಪಟ್ಟಿಯನ್ನು ರಚಿಸಲು ಧ್ವನಿ ಅಥವಾ ಪಠ್ಯ ಬಳಸಿ',
    select_language: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    describe_method: 'ನಿಮ್ಮ ಉತ್ಪನ್ನವನ್ನು ಹೇಗೆ ವಿವರಿಸಲು ಬಯಸುತ್ತೀರಿ?',
    voice: 'ಧ್ವನಿ',
    text: 'ಪಠ್ಯ',
    speak_to_describe: 'ವಿವರಿಸಲು ಮಾತನಾಡಿ',
    type_description: 'ವಿವರಣೆ ಟೈಪ್ ಮಾಡಿ',
    describe_product: 'ನಿಮ್ಮ ಉತ್ಪನ್ನವನ್ನು ವಿವರಿಸಿ',
    describe_placeholder: 'ಉದಾ., "ರಾಜಸ್ಥಾನದಿಂದ ಸಾಂಪ್ರದಾಯಿಕ ಬ್ಲಾಕ್ ಪ್ರಿಂಟ್ ವಿನ್ಯಾಸದೊಂದಿಗೆ ಕೈಯಿಂದ ತಯಾರಿಸಿದ ಹತ್ತಿ ಸೀರೆ..."',
    add_product_image: 'ಉತ್ಪನ್ನ ಚಿತ್ರ ಸೇರಿಸಿ (ಐಚ್ಛಿಕ)',
    upload: 'ಅಪ್‌ಲೋಡ್',
    generate_with_ai: 'AI ನೊಂದಿಗೆ ಉತ್ಪನ್ನ ವಿವರಗಳನ್ನು ರಚಿಸಿ',
    ai_generating: 'AI ರಚಿಸುತ್ತಿದೆ...',
    ai_generated_success: '✨ AI ಉತ್ಪನ್ನ ಪಟ್ಟಿಯನ್ನು ರಚಿಸಿದೆ! ಕೆಳಗೆ ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸಂಪಾದಿಸಿ.',
    review_edit: 'ಪರಿಶೀಲಿಸಿ & ಸಂಪಾದಿಸಿ',
    back_to_input: '← ಇನ್‌ಪುಟ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    product_image: 'ಉತ್ಪನ್ನ ಚಿತ್ರ',
    product_name: 'ಉತ್ಪನ್ನ ಹೆಸರು',
    enter_product_name: 'ಉತ್ಪನ್ನ ಹೆಸರು ನಮೂದಿಸಿ',
    description: 'ವಿವರಣೆ',
    describe_your_product: 'ನಿಮ್ಮ ಉತ್ಪನ್ನವನ್ನು ವಿವರಿಸಿ',
    category: 'ವರ್ಗ',
    select_category: 'ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    price: 'ಬೆಲೆ',
    enter_price: 'ಬೆಲೆ ನಮೂದಿಸಿ',
    language: 'ಭಾಷೆ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    add_to_catalog: '✓ ಕ್ಯಾಟಲಾಗ್‌ಗೆ ಸೇರಿಸಿ',
    adding_product: 'ಉತ್ಪನ್ನ ಸೇರಿಸುತ್ತಿದೆ...',
    save_changes: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    tip_describe: '💡 ಸಲಹೆ: ಉತ್ತಮ AI ಪಟ್ಟಿಗಳಿಗಾಗಿ ನಿಮ್ಮ ಉತ್ಪನ್ನವನ್ನು ವಿವರವಾಗಿ ವಿವರಿಸಿ',
    supports_voice: 'ಹಿಂದಿ, ತಮಿಳು, ತೆಲುಗು, ಕನ್ನಡ ಮತ್ತು ಬೆಂಗಾಲಿಯಲ್ಲಿ ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಬೆಂಬಲಿತ',
    step_describe: 'ವಿವರಿಸಿ',
    step_review: 'ಪರಿಶೀಲಿಸಿ & ಉಳಿಸಿ',
    please_describe: 'ದಯವಿಟ್ಟು ಮೊದಲು ಧ್ವನಿ ಅಥವಾ ಪಠ್ಯದ ಮೂಲಕ ನಿಮ್ಮ ಉತ್ಪನ್ನವನ್ನು ವಿವರಿಸಿ',
    failed_generate: 'ಉತ್ಪನ್ನ ವಿವರಗಳನ್ನು ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    voice_commands: 'ಧ್ವನಿ ಆದೇಶಗಳು',
    voice_commands_desc: '"ಧ್ವನಿ ಅಪ್‌ಡೇಟ್" ಕ್ಲಿಕ್ ಮಾಡಿ ಮತ್ತು ಹೇಳಿ:',
    voice_update: 'ಧ್ವನಿ ಅಪ್‌ಡೇಟ್',
    listening_text: 'ಕೇಳುತ್ತಿದೆ...',
    voice_example_price: '"ಬೆಲೆ 500 ಗೆ ಬದಲಾಯಿಸಿ"',
    voice_example_category: '"ವರ್ಗ ಬಟ್ಟೆಗೆ ಬದಲಾಯಿಸಿ"',
    voice_example_name: '"ಹೆಸರು ಸಿಲ್ಕ್ ಸೀರೆಗೆ ಬದಲಾಯಿಸಿ"',
    voice_example_save: '"ಉಳಿಸಿ" - ಉಳಿಸಿ ಮತ್ತು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ',
    voice_example_cancel: '"ರದ್ದುಮಾಡಿ" ಅಥವಾ "ಹಿಂತಿರುಗಿ" - ಉಳಿಸದೆ ಹಿಂತಿರುಗಿ',
    // Export
    export_platforms_title: 'ಮಾರಾಟ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗಳಿಗೆ ರಫ್ತು ಮಾಡಿ',
    how_to_upload: 'ಮಾರಾಟ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗಳಿಗೆ ಹೇಗೆ ಅಪ್‌ಲೋಡ್ ಮಾಡುವುದು',
    step1_export: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್-ನಿರ್ದಿಷ್ಟ ಸ್ವರೂಪದಲ್ಲಿ ನಿಮ್ಮ ಕ್ಯಾಟಲಾಗ್ ಅನ್ನು ರಫ್ತು ಮಾಡಿ',
    step2_login: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಮಾರಾಟಗಾರ ಖಾತೆಗೆ ಲಾಗಿನ್ ಆಗಿ',
    step3_bulk: '"ಬಲ್ಕ್ ಅಪ್‌ಲೋಡ್" ಅಥವಾ "ಉತ್ಪನ್ನಗಳನ್ನು ಆಮದು ಮಾಡಿ" ವಿಭಾಗಕ್ಕೆ ಹೋಗಿ',
    step4_upload: 'ರಫ್ತು ಮಾಡಿದ ಫೈಲ್ ಅನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಪಟ್ಟಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    pro_tip: '💡 ಪ್ರೊ ಟಿಪ್: ಭವಿಷ್ಯದ ಆವೃತ್ತಿಗಳಲ್ಲಿ, ಒಂದು-ಕ್ಲಿಕ್ ಪ್ರಕಟಣೆಗಾಗಿ ನೇರ API ಏಕೀಕರಣವನ್ನು ಬೆಂಬಲಿಸುತ್ತೇವೆ!',
  },
  bn: {
    nav_home: 'হোম',
    nav_dashboard: 'আমার তালিকা',
    nav_demo: 'ডেমো',
    nav_login: 'লগইন',
    nav_signup: 'সাইন আপ',
    nav_logout: 'লগআউট',
    hero_title: 'স্থানীয় বিক্রেতাদের জন্য AI ডিজিটাল ক্যাটালগ',
    hero_subtitle: 'আপনার ভাষায় ভয়েস ব্যবহার করে পেশাদার তালিকা তৈরি করুন',
    get_started: 'বিনামূল্যে শুরু করুন',
    try_demo: 'ডেমো দেখুন',
    choose_language: 'আপনার ভাষা বেছে নিন',
    free_to_use: 'বিনামূল্যে ব্যবহার',
    indian_languages: '৬টি ভারতীয় ভাষা',
    ai_powered: 'AI-চালিত',
    accessibility_ready: 'অ্যাক্সেসিবিলিটি প্রস্তুত',
    voice_commands_enabled: 'ভয়েস কমান্ড সক্রিয়',
    voice_commands_help: 'ভয়েস কমান্ড শিখতে "সাহায্য" বলুন • দৃষ্টি প্রতিবন্ধীদের জন্য অ্যাক্সেসযোগ্য',
    powerful_features: 'ছোট ব্যবসার জন্য শক্তিশালী বৈশিষ্ট্য',
    features_subtitle: 'কোনো প্রযুক্তিগত জ্ঞান ছাড়াই পেশাদার পণ্য ক্যাটালগ তৈরি করতে যা প্রয়োজন সব কিছু',
    feature_voice_title: 'ভয়েস ইনপুট',
    feature_voice_desc: 'আপনার পণ্য বর্ণনা করতে কথা বলুন। আমাদের AI হিন্দি, তামিল, তেলুগু, কন্নড়, বাংলা এবং ইংরেজি বোঝে।',
    feature_photo_title: 'ফটো ক্যাপচার',
    feature_photo_desc: 'আপনার পণ্যের ছবি তুলুন এবং AI স্বয়ংক্রিয়ভাবে বিবরণ তৈরি করবে।',
    feature_ai_title: 'AI বিবরণ',
    feature_ai_desc: 'পেশাদার পণ্য বিবরণ, বিভাগ এবং মূল্য পরামর্শ তাৎক্ষণিকভাবে পান।',
    feature_multilang_title: 'বহু-ভাষা',
    feature_multilang_desc: 'আপনার স্থানীয় ভাষায় ক্যাটালগ তৈরি করুন। আরও গ্রাহকদের কাছে পৌঁছাতে স্বয়ংক্রিয় অনুবাদ।',
    feature_mobile_title: 'মোবাইল-প্রথম',
    feature_mobile_desc: 'স্মার্টফোনের জন্য ডিজাইন করা। বেসিক ফোন এবং ধীর ইন্টারনেটেও সহজ।',
    feature_share_title: 'যেকোনো জায়গায় শেয়ার করুন',
    feature_share_desc: 'গ্রাহকদের কাছে পৌঁছাতে WhatsApp, Facebook বা যেকোনো প্ল্যাটফর্মে আপনার ক্যাটালগ লিঙ্ক শেয়ার করুন।',
    challenges_title: 'আমরা যে চ্যালেঞ্জগুলো সমাধান করি',
    challenges_subtitle: 'ছোট ব্যবসাগুলো ডিজিটাল হতে গিয়ে প্রকৃত বাধার সম্মুখীন হয়',
    challenge_skills_title: 'কম ডিজিটাল দক্ষতা',
    challenge_skills_desc: 'অনেক দোকানদার প্রযুক্তিকে বিভ্রান্তিকর মনে করেন। জটিল অ্যাপ এবং ফর্ম অপ্রতিরোধ্য।',
    challenge_skills_solution: 'আমাদের ভয়েস-প্রথম পদ্ধতিতে টাইপিং বা প্রযুক্তিগত জ্ঞানের প্রয়োজন নেই।',
    challenge_language_title: 'ভাষার বাধা',
    challenge_language_desc: 'বেশিরভাগ ডিজিটাল টুল ইংরেজিতে, যা স্থানীয় ভাষা পছন্দকারী লক্ষ লক্ষ মানুষকে বাদ দেয়।',
    challenge_language_solution: 'হিন্দি, তামিল, তেলুগু, কন্নড়, বাংলা এবং ইংরেজির জন্য সম্পূর্ণ সমর্থন।',
    challenge_presence_title: 'অনলাইন উপস্থিতি নেই',
    challenge_presence_desc: 'ক্যাটালগ ছাড়া, ব্যবসাগুলো অনলাইনে নতুন গ্রাহকদের কাছে পৌঁছানোর সুযোগ হারায়।',
    challenge_presence_solution: 'দিন নয়, মিনিটে শেয়ারযোগ্য ক্যাটালগ তৈরি করুন।',
    how_it_works: 'এটি কীভাবে কাজ করে',
    how_it_works_subtitle: '২ মিনিটের মধ্যে আপনার প্রথম পণ্য তালিকা তৈরি করুন',
    step1_title: 'ভাষা বেছে নিন',
    step1_desc: '৬টি ভারতীয় ভাষা থেকে আপনার পছন্দের ভাষা বেছে নিন',
    step2_title: 'পণ্য বর্ণনা করুন',
    step2_desc: 'কথা বলুন, টাইপ করুন বা আপনার পণ্যের ছবি তুলুন',
    step3_title: 'AI তৈরি করে',
    step3_desc: 'AI পেশাদার নাম, বিবরণ ও বিভাগ তৈরি করে',
    step4_title: 'ক্যাটালগ শেয়ার করুন',
    step4_desc: 'গ্রাহকদের সাথে আপনার ক্যাটালগ লিঙ্ক শেয়ার করুন',
    stat_languages: 'সমর্থিত ভাষা',
    stat_inputs: 'ইনপুট পদ্ধতি',
    stat_categories: 'পণ্য বিভাগ',
    stat_products: 'আপনি যোগ করতে পারেন পণ্য',
    cta_title: 'আপনার ব্যবসা ডিজিটাল করতে প্রস্তুত?',
    cta_subtitle: 'ইতিমধ্যে ডিজিটাল ক্যাটালগ এজেন্ট ব্যবহারকারী হাজার হাজার ছোট ব্যবসার সাথে যোগ দিন। এটি বিনামূল্যে, সহজ এবং আপনার ভাষায় কাজ করে।',
    cta_button: 'এখনই আপনার ক্যাটালগ তৈরি করুন',
    cta_footer: 'ডিজিটাল ইন্ডিয়া উদ্যোগকে সমর্থন • ভারতের জন্য তৈরি 🇮🇳',
    my_catalog: 'আমার তালিকা',
    products_count: 'পণ্য',
    publish_platforms: 'প্ল্যাটফর্মে প্রকাশ করুন',
    add_product: 'পণ্য যোগ করুন',
    no_products: 'এখনও কোনো পণ্য নেই। আপনার প্রথম পণ্য যোগ করুন!',
    add_first: 'প্রথম পণ্য যোগ করুন',
    edit: 'সম্পাদনা',
    delete: 'মুছুন',
    deleting: 'মুছছে...',
    add_new_product: 'নতুন পণ্য যোগ করুন',
    product_name: 'পণ্যের নাম',
    description: 'বিবরণ',
    category: 'বিভাগ',
    price: 'দাম',
    language: 'ভাষা',
    save_product: 'পণ্য সংরক্ষণ করুন',
    saving: 'সংরক্ষণ করছে...',
    voice_input: 'ভয়েস ইনপুট',
    tap_to_speak: 'কথা বলতে ট্যাপ করুন',
    listening: 'শুনছে...',
    stop: 'থামুন',
    take_photo: 'ছবি তুলুন',
    upload_image: 'ছবি আপলোড করুন',
    capture: 'ক্যাপচার',
    retake: 'আবার তুলুন',
    use_photo: 'ছবি ব্যবহার করুন',
    publish_title: 'বিক্রেতা প্ল্যাটফর্মে প্রকাশ করুন',
    publish_subtitle: 'আপনার ক্যাটালগ ই-কমার্স প্ল্যাটফর্মে রপ্তানি করুন',
    your_catalog: 'আপনার ক্যাটালগ',
    products_ready: 'পণ্য প্রকাশের জন্য প্রস্তুত',
    view_products: 'পণ্য দেখুন',
    share_link: 'শেয়ারযোগ্য লিঙ্ক',
    share_link_desc: 'গ্রাহকদের সাথে এই লিঙ্ক শেয়ার করুন',
    copy: 'কপি',
    copied: 'কপি হয়েছে!',
    export: 'রপ্তানি',
    exporting: 'রপ্তানি করছে...',
    exported: 'রপ্তানি হয়েছে',
    share: 'শেয়ার',
    login_title: 'স্বাগতম',
    signup_title: 'অ্যাকাউন্ট তৈরি করুন',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    confirm_password: 'পাসওয়ার্ড নিশ্চিত করুন',
    login_btn: 'লগইন',
    signup_btn: 'সাইন আপ',
    no_account: 'অ্যাকাউন্ট নেই?',
    have_account: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    // Public Catalog
    catalog_not_found: 'ক্যাটালগ পাওয়া যায়নি',
    products_available: 'পণ্য উপলব্ধ',
    share_catalog: 'ক্যাটালগ শেয়ার করুন',
    link_copied: 'লিঙ্ক কপি হয়েছে!',
    no_products_catalog: 'এই ক্যাটালগে এখনও কোনো পণ্য নেই।',
    tap_view_details: 'বিস্তারিত দেখতে ট্যাপ করুন',
    product_details: 'পণ্যের বিবরণ',
    sold_by: 'বিক্রেতা',
    contact_whatsapp: 'WhatsApp-এ বিক্রেতার সাথে যোগাযোগ করুন',
    whatsapp_note: 'আগে থেকে পূরণ করা বার্তা সহ WhatsApp খুলবে',
    payment_options: 'পেমেন্ট অপশন',
    pay_via_upi: 'UPI দিয়ে পেমেন্ট করুন',
    scan_to_pay: 'পেমেন্ট করতে স্ক্যান করুন',
    powered_by: 'ডিজিটাল ক্যাটালগ এজেন্ট দ্বারা পরিচালিত',
    create_own_catalog: 'আপনার নিজের ক্যাটালগ তৈরি করুন',
    voice_help: 'বলুন: "ড্যাশবোর্ড যাও", "পণ্য যোগ করো", "রপ্তানি করো", "লগআউট"',
    command_recognized: 'কমান্ড চিনতে পেরেছে',
    command_not_recognized: 'কমান্ড চিনতে পারেনি। আবার চেষ্টা করুন।',
    // Payment Settings
    payment_title: 'পেমেন্ট সেটিংস',
    payment_subtitle: 'গ্রাহকদের কাছ থেকে পেমেন্ট পেতে আপনার পেমেন্ট বিবরণ যোগ করুন',
    upi: 'ইউপিআই',
    bank_account: 'ব্যাংক অ্যাকাউন্ট',
    qr_code: 'কিউআর কোড',
    upi_id: 'ইউপিআই আইডি',
    upi_name: 'ইউপিআইতে নাম',
    add_upi: 'আরেকটি ইউপিআই যোগ করুন',
    account_name: 'অ্যাকাউন্ট হোল্ডারের নাম',
    account_number: 'অ্যাকাউন্ট নম্বর',
    ifsc_code: 'আইএফএসসি কোড',
    bank_name: 'ব্যাংকের নাম',
    upload_qr: 'কিউআর কোড আপলোড করুন',
    save_payment: 'পেমেন্ট বিবরণ সংরক্ষণ করুন',
    payment_saved: 'পেমেন্ট বিবরণ সফলভাবে সংরক্ষিত হয়েছে!',
    remove: 'সরান',
    saving_text: 'সংরক্ষণ করছে...',
    // Add/Edit Product
    add_new_product: 'নতুন পণ্য যোগ করুন',
    edit_product: 'পণ্য সম্পাদনা করুন',
    use_voice_text: 'আপনার পণ্য তালিকা তৈরি করতে ভয়েস বা টেক্সট ব্যবহার করুন',
    select_language: 'আপনার ভাষা বেছে নিন',
    describe_method: 'আপনি কীভাবে আপনার পণ্য বর্ণনা করতে চান?',
    voice: 'ভয়েস',
    text: 'টেক্সট',
    speak_to_describe: 'বর্ণনা করতে বলুন',
    type_description: 'বিবরণ টাইপ করুন',
    describe_product: 'আপনার পণ্য বর্ণনা করুন',
    describe_placeholder: 'যেমন, "রাজস্থান থেকে ঐতিহ্যবাহী ব্লক প্রিন্ট ডিজাইনের হাতে তৈরি সুতি শাড়ি..."',
    add_product_image: 'পণ্যের ছবি যোগ করুন (ঐচ্ছিক)',
    upload: 'আপলোড',
    generate_with_ai: 'AI দিয়ে পণ্যের বিবরণ তৈরি করুন',
    ai_generating: 'AI তৈরি করছে...',
    ai_generated_success: '✨ AI পণ্য তালিকা তৈরি করেছে! নিচে পর্যালোচনা করুন এবং সম্পাদনা করুন।',
    review_edit: 'পর্যালোচনা ও সম্পাদনা',
    back_to_input: '← ইনপুটে ফিরে যান',
    product_image: 'পণ্যের ছবি',
    product_name: 'পণ্যের নাম',
    enter_product_name: 'পণ্যের নাম লিখুন',
    description: 'বিবরণ',
    describe_your_product: 'আপনার পণ্য বর্ণনা করুন',
    category: 'বিভাগ',
    select_category: 'বিভাগ নির্বাচন করুন',
    price: 'দাম',
    enter_price: 'দাম লিখুন',
    language: 'ভাষা',
    cancel: 'বাতিল',
    add_to_catalog: '✓ ক্যাটালগে যোগ করুন',
    adding_product: 'পণ্য যোগ করছে...',
    save_changes: 'পরিবর্তন সংরক্ষণ করুন',
    tip_describe: '💡 টিপ: ভালো AI তালিকার জন্য আপনার পণ্য বিস্তারিতভাবে বর্ণনা করুন',
    supports_voice: 'হিন্দি, তামিল, তেলুগু, কন্নড় এবং বাংলায় ভয়েস ইনপুট সমর্থিত',
    step_describe: 'বর্ণনা করুন',
    step_review: 'পর্যালোচনা ও সংরক্ষণ',
    please_describe: 'অনুগ্রহ করে প্রথমে ভয়েস বা টেক্সট দিয়ে আপনার পণ্য বর্ণনা করুন',
    failed_generate: 'পণ্যের বিবরণ তৈরি করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
    voice_commands: 'ভয়েস কমান্ড',
    voice_commands_desc: '"ভয়েস আপডেট" ক্লিক করুন এবং বলুন:',
    voice_update: 'ভয়েস আপডেট',
    listening_text: 'শুনছে...',
    voice_example_price: '"দাম 500 করো"',
    voice_example_category: '"বিভাগ পোশাক করো"',
    voice_example_name: '"নাম সিল্ক শাড়ি করো"',
    voice_example_save: '"সেভ করো" - সংরক্ষণ করে ড্যাশবোর্ডে যাও',
    voice_example_cancel: '"বাতিল করো" বা "ফিরে যাও" - সংরক্ষণ না করে ফিরে যাও',
    // Export
    export_platforms_title: 'বিক্রেতা প্ল্যাটফর্মে রপ্তানি করুন',
    how_to_upload: 'বিক্রেতা প্ল্যাটফর্মে কীভাবে আপলোড করবেন',
    step1_export: 'প্ল্যাটফর্ম-নির্দিষ্ট ফরম্যাটে আপনার ক্যাটালগ রপ্তানি করুন',
    step2_login: 'প্ল্যাটফর্মে আপনার বিক্রেতা অ্যাকাউন্টে লগইন করুন',
    step3_bulk: '"বাল্ক আপলোড" বা "পণ্য আমদানি" বিভাগে যান',
    step4_upload: 'রপ্তানি করা ফাইল আপলোড করুন এবং আপনার তালিকা পর্যালোচনা করুন',
    pro_tip: '💡 প্রো টিপ: ভবিষ্যত সংস্করণে, এক-ক্লিকে প্রকাশের জন্য সরাসরি API ইন্টিগ্রেশন সমর্থন করব!',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('appLanguage') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
