import { createContext, useContext, useState, useEffect } from 'react';

// Translations for all UI elements
const translations = {
  en: {
    // Navigation
    nav_home: 'Home',
    nav_dashboard: 'My Catalog',
    nav_demo: 'Try Demo',
    nav_login: 'Login',
    nav_signup: 'Sign Up',
    nav_logout: 'Logout',
    // Landing
    hero_title: 'AI-Powered Digital Catalog for Local Sellers',
    hero_subtitle: 'Create professional product listings using voice in your language',
    get_started: 'Get Started Free',
    try_demo: 'Try Demo',
    choose_language: 'Choose your language',
    free_to_use: 'Free to Use',
    indian_languages: '6 Indian Languages',
    ai_powered: 'AI-Powered',
    accessibility_ready: 'Accessibility Ready',
    voice_commands_enabled: 'Voice Commands Enabled',
    voice_commands_help: 'Say "Help" to learn voice commands • Accessible for visually impaired users',
    powerful_features: 'Powerful Features for Small Businesses',
    features_subtitle: 'Everything you need to create professional product catalogs without any technical knowledge',
    feature_voice_title: 'Voice Input',
    feature_voice_desc: 'Simply speak to describe your products. Our AI understands Hindi, Tamil, Telugu, Kannada, Bengali, and English.',
    feature_photo_title: 'Photo Capture',
    feature_photo_desc: 'Take a photo of your product and let AI generate the description automatically.',
    feature_ai_title: 'AI Descriptions',
    feature_ai_desc: 'Get professional product descriptions, categories, and pricing suggestions instantly.',
    feature_multilang_title: 'Multi-Language',
    feature_multilang_desc: 'Create catalogs in your local language. Auto-translate to reach more customers.',
    feature_mobile_title: 'Mobile-First',
    feature_mobile_desc: 'Designed for smartphones. Easy to use even with basic phones and slow internet.',
    feature_share_title: 'Share Anywhere',
    feature_share_desc: 'Share your catalog link on WhatsApp, Facebook, or any platform to reach customers.',
    challenges_title: 'Challenges We Solve',
    challenges_subtitle: 'Small businesses face real barriers to going digital',
    challenge_skills_title: 'Low Digital Skills',
    challenge_skills_desc: 'Many shopkeepers find technology confusing. Complex apps and forms are overwhelming.',
    challenge_skills_solution: 'Our voice-first approach needs no typing or technical knowledge.',
    challenge_language_title: 'Language Barriers',
    challenge_language_desc: 'Most digital tools are in English, excluding millions who prefer local languages.',
    challenge_language_solution: 'Full support for Hindi, Tamil, Telugu, Kannada, Bengali, and English.',
    challenge_presence_title: 'No Online Presence',
    challenge_presence_desc: 'Without a catalog, businesses miss opportunities to reach new customers online.',
    challenge_presence_solution: 'Create shareable catalogs in minutes, not days.',
    how_it_works: 'How It Works',
    how_it_works_subtitle: 'Create your first product listing in under 2 minutes',
    step1_title: 'Choose Language',
    step1_desc: 'Select your preferred language from 6 Indian languages',
    step2_title: 'Describe Product',
    step2_desc: 'Speak, type, or take a photo of your product',
    step3_title: 'AI Generates',
    step3_desc: 'AI creates professional name, description & category',
    step4_title: 'Share Catalog',
    step4_desc: 'Share your catalog link with customers',
    stat_languages: 'Languages Supported',
    stat_inputs: 'Input Methods',
    stat_categories: 'Product Categories',
    stat_products: 'Products You Can Add',
    cta_title: 'Ready to Digitize Your Business?',
    cta_subtitle: 'Join thousands of small businesses already using Digital Catalog Agent. It\'s free, easy, and works in your language.',
    cta_button: 'Create Your Catalog Now',
    cta_footer: 'Supporting Digital India initiative • Made for Bharat 🇮🇳',
    // Dashboard
    my_catalog: 'My Catalog',
    products_count: 'products',
    publish_platforms: 'Publish to Platforms',
    add_product: 'Add Product',
    no_products: 'No products yet. Start by adding your first product!',
    add_first: 'Add Your First Product',
    edit: 'Edit',
    delete: 'Delete',
    deleting: 'Deleting...',
    // Add Product
    add_new_product: 'Add New Product',
    product_name: 'Product Name',
    description: 'Description',
    category: 'Category',
    price: 'Price',
    language: 'Language',
    save_product: 'Save Product',
    saving: 'Saving...',
    select_language: 'Select Your Language',
    describe_method: 'How would you like to describe your product?',
    voice: 'Voice',
    text: 'Text',
    camera: 'Camera',
    speak_to_describe: 'Speak to describe',
    type_description: 'Type description',
    take_a_photo: 'Take a photo',
    describe_product: 'Describe your product',
    describe_placeholder: 'E.g., "Handmade cotton saree with traditional block print design from Rajasthan, perfect for festivals..."',
    add_description_photo: 'Add a description for better AI results',
    describe_photo: 'Describe what\'s in the photo...',
    generate_with_ai: 'Generate Product Details with AI',
    ai_generating: 'AI is generating...',
    ai_success: '✨ AI generated English product listing from your voice input! Review and edit below.',
    review_edit: 'Review & Edit Details',
    back_to_input: '← Back to Input',
    product_image: 'Product Image',
    enter_product_name: 'Enter product name',
    describe_your_product: 'Describe your product',
    select_category: 'Select category',
    enter_price: 'Enter price',
    cancel: 'Cancel',
    add_to_catalog: '✓ Add Product to Catalog',
    adding_product: 'Adding Product...',
    tip_describe: '💡 Tip: Describe your product in detail for better AI-generated listings',
    supports_voice: 'Supports voice input in Hindi, Tamil, Telugu, Kannada, and Bengali',
    step_describe: 'Describe',
    step_review: 'Review & Save',
    please_describe: 'Please describe your product first using voice or text',
    failed_generate: 'Failed to generate product details. Please try again.',
    // Voice
    voice_input: 'Voice Input',
    tap_to_speak: 'Tap to speak',
    listening: 'Listening...',
    stop: 'Stop',
    // Camera
    take_photo: 'Take Photo',
    upload_image: 'Upload Image',
    capture: 'Capture',
    retake: 'Retake',
    use_photo: 'Use Photo',
    // Export
    publish_title: 'Publish to Seller Platforms',
    publish_subtitle: 'Export your catalog to major e-commerce platforms',
    your_catalog: 'Your Catalog',
    products_ready: 'products ready to publish',
    view_products: 'View Products',
    share_link: 'Shareable Catalog Link',
    share_link_desc: 'Share this link with customers',
    copy: 'Copy',
    copied: 'Copied!',
    export: 'Export',
    exporting: 'Exporting...',
    exported: 'Exported',
    share: 'Share',
    // Auth
    login_title: 'Welcome Back',
    signup_title: 'Create Account',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    full_name: 'Full Name',
    login_btn: 'Login',
    signup_btn: 'Sign Up',
    no_account: "Don't have an account?",
    have_account: 'Already have an account?',
    enter_name: 'Enter your name',
    enter_email: 'Enter your email',
    enter_password: 'Enter your password',
    confirm_password_placeholder: 'Confirm your password',
    password_min: 'At least 8 characters',
    creating_account: 'Creating Account...',
    logging_in: 'Logging in...',
    login_subtitle: 'Login to manage your catalog',
    signup_subtitle: 'Start building your digital catalog',
    something_wrong: 'Something went wrong. Please try again.',
    // Dashboard
    share_catalog: 'Share Catalog',
    link_copied: 'Link Copied!',
    payment: 'Payment',
    delete_confirm: 'Are you sure you want to delete this product?',
    failed_load: 'Failed to load products. Please try again.',
    failed_delete: 'Failed to delete product. Please try again.',
    my_catalog_title: 'My Product Catalog',
    share_catalog_title: 'My Product Catalog',
    share_catalog_text: 'Check out my product catalog!',
    // Voice Commands
    voice_help: 'Say: "go to dashboard", "add product", "export catalog", "logout"',
    command_recognized: 'Command recognized',
    command_not_recognized: 'Command not recognized. Try again.',
  },
  hi: {
    nav_home: 'होम',
    nav_dashboard: 'मेरी सूची',
    nav_demo: 'डेमो देखें',
    nav_login: 'लॉगिन',
    nav_signup: 'साइन अप',
    nav_logout: 'लॉगआउट',
    hero_title: 'स्थानीय विक्रेताओं के लिए AI-संचालित डिजिटल कैटलॉग',
    hero_subtitle: 'अपनी भाषा में आवाज़ का उपयोग करके पेशेवर उत्पाद सूची बनाएं',
    get_started: 'मुफ्त शुरू करें',
    try_demo: 'डेमो देखें',
    my_catalog: 'मेरी सूची',
    products_count: 'उत्पाद',
    publish_platforms: 'प्लेटफॉर्म पर प्रकाशित करें',
    add_product: 'उत्पाद जोड़ें',
    no_products: 'अभी कोई उत्पाद नहीं है। अपना पहला उत्पाद जोड़कर शुरू करें!',
    add_first: 'अपना पहला उत्पाद जोड़ें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    deleting: 'हटा रहे हैं...',
    add_new_product: 'नया उत्पाद जोड़ें',
    product_name: 'उत्पाद का नाम',
    description: 'विवरण',
    category: 'श्रेणी',
    price: 'कीमत',
    language: 'भाषा',
    save_product: 'उत्पाद सहेजें',
    saving: 'सहेज रहे हैं...',
    select_language: 'अपनी भाषा चुनें',
    describe_method: 'आप अपने उत्पाद का वर्णन कैसे करना चाहेंगे?',
    voice: 'आवाज़',
    text: 'टेक्स्ट',
    camera: 'कैमरा',
    speak_to_describe: 'बोलकर बताएं',
    type_description: 'टाइप करें',
    take_a_photo: 'फोटो लें',
    describe_product: 'अपने उत्पाद का वर्णन करें',
    describe_placeholder: 'जैसे: "राजस्थान से पारंपरिक ब्लॉक प्रिंट डिज़ाइन वाली हस्तनिर्मित सूती साड़ी, त्योहारों के लिए बिल्कुल सही..."',
    add_description_photo: 'बेहतर AI परिणामों के लिए विवरण जोड़ें',
    describe_photo: 'फोटो में क्या है बताएं...',
    generate_with_ai: 'AI से उत्पाद विवरण बनाएं',
    ai_generating: 'AI बना रहा है...',
    ai_success: '✨ AI ने आपकी आवाज़ से अंग्रेज़ी उत्पाद सूची बनाई! नीचे देखें और संपादित करें।',
    review_edit: 'समीक्षा करें और संपादित करें',
    back_to_input: '← वापस जाएं',
    product_image: 'उत्पाद छवि',
    enter_product_name: 'उत्पाद का नाम दर्ज करें',
    describe_your_product: 'अपने उत्पाद का वर्णन करें',
    select_category: 'श्रेणी चुनें',
    enter_price: 'कीमत दर्ज करें',
    cancel: 'रद्द करें',
    add_to_catalog: '✓ कैटलॉग में जोड़ें',
    adding_product: 'उत्पाद जोड़ रहे हैं...',
    tip_describe: '💡 सुझाव: बेहतर AI सूची के लिए अपने उत्पाद का विस्तार से वर्णन करें',
    supports_voice: 'हिंदी, तमिल, तेलुगु, कन्नड़ और बंगाली में आवाज़ इनपुट समर्थित',
    step_describe: 'वर्णन करें',
    step_review: 'समीक्षा और सहेजें',
    please_describe: 'कृपया पहले आवाज़ या टेक्स्ट से अपने उत्पाद का वर्णन करें',
    failed_generate: 'उत्पाद विवरण बनाने में विफल। कृपया पुनः प्रयास करें।',
    voice_input: 'आवाज़ इनपुट',
    tap_to_speak: 'बोलने के लिए टैप करें',
    listening: 'सुन रहे हैं...',
    stop: 'रुकें',
    take_photo: 'फोटो लें',
    upload_image: 'छवि अपलोड करें',
    capture: 'कैप्चर',
    retake: 'फिर से लें',
    use_photo: 'फोटो उपयोग करें',
    publish_title: 'विक्रेता प्लेटफॉर्म पर प्रकाशित करें',
    publish_subtitle: 'अपनी सूची को प्रमुख ई-कॉमर्स प्लेटफॉर्म पर निर्यात करें',
    your_catalog: 'आपकी सूची',
    products_ready: 'उत्पाद प्रकाशित करने के लिए तैयार',
    view_products: 'उत्पाद देखें',
    share_link: 'साझा करने योग्य लिंक',
    share_link_desc: 'ग्राहकों के साथ यह लिंक साझा करें',
    copy: 'कॉपी',
    copied: 'कॉपी हो गया!',
    export: 'निर्यात',
    exporting: 'निर्यात हो रहा है...',
    exported: 'निर्यात हो गया',
    share: 'साझा करें',
    login_title: 'वापस स्वागत है',
    signup_title: 'खाता बनाएं',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirm_password: 'पासवर्ड की पुष्टि करें',
    login_btn: 'लॉगिन',
    signup_btn: 'साइन अप',
    no_account: 'खाता नहीं है?',
    have_account: 'पहले से खाता है?',
    voice_help: 'बोलें: "डैशबोर्ड जाओ", "उत्पाद जोड़ो", "निर्यात करो", "लॉगआउट"',
    command_recognized: 'आदेश पहचाना गया',
    command_not_recognized: 'आदेश नहीं पहचाना। फिर से कोशिश करें।',
  },
  ta: {
    nav_home: 'முகப்பு',
    nav_dashboard: 'என் பட்டியல்',
    nav_demo: 'டெமோ',
    nav_login: 'உள்நுழை',
    nav_signup: 'பதிவு செய்',
    nav_logout: 'வெளியேறு',
    hero_title: 'உள்ளூர் விற்பனையாளர்களுக்கான AI டிஜிட்டல் கேட்டலாக்',
    hero_subtitle: 'உங்கள் மொழியில் குரல் மூலம் தொழில்முறை பட்டியல்களை உருவாக்குங்கள்',
    get_started: 'இலவசமாக தொடங்கு',
    try_demo: 'டெமோ பார்',
    choose_language: 'உங்கள் மொழியை தேர்வு செய்யவும்',
    free_to_use: 'இலவசம்',
    indian_languages: '6 இந்திய மொழிகள்',
    ai_powered: 'AI இயக்கம்',
    accessibility_ready: 'அணுகல் தயார்',
    voice_commands_enabled: 'குரல் கட்டளைகள் இயக்கப்பட்டது',
    voice_commands_help: 'குரல் கட்டளைகளை அறிய "உதவி" என்று சொல்லுங்கள் • பார்வை குறைபாடு உள்ளவர்களுக்கு அணுகக்கூடியது',
    powerful_features: 'சிறு வணிகங்களுக்கான சக்திவாய்ந்த அம்சங்கள்',
    features_subtitle: 'தொழில்நுட்ப அறிவு இல்லாமல் தொழில்முறை தயாரிப்பு பட்டியல்களை உருவாக்க தேவையான அனைத்தும்',
    feature_voice_title: 'குரல் உள்ளீடு',
    feature_voice_desc: 'உங்கள் பொருட்களை விவரிக்க பேசுங்கள். எங்கள் AI இந்தி, தமிழ், தெலுங்கு, கன்னடம், வங்காளம் மற்றும் ஆங்கிலம் புரிந்துகொள்கிறது.',
    feature_photo_title: 'புகைப்படம் எடுப்பு',
    feature_photo_desc: 'உங்கள் பொருளின் புகைப்படம் எடுங்கள், AI தானாகவே விவரத்தை உருவாக்கும்.',
    feature_ai_title: 'AI விவரங்கள்',
    feature_ai_desc: 'தொழில்முறை தயாரிப்பு விவரங்கள், வகைகள் மற்றும் விலை பரிந்துரைகளை உடனடியாக பெறுங்கள்.',
    feature_multilang_title: 'பல மொழி',
    feature_multilang_desc: 'உங்கள் உள்ளூர் மொழியில் பட்டியல்களை உருவாக்குங்கள். அதிக வாடிக்கையாளர்களை அடைய தானாக மொழிபெயர்க்கவும்.',
    feature_mobile_title: 'மொபைல்-முதல்',
    feature_mobile_desc: 'ஸ்மார்ட்போன்களுக்காக வடிவமைக்கப்பட்டது. அடிப்படை போன்கள் மற்றும் மெதுவான இணையத்திலும் எளிதாக பயன்படுத்தலாம்.',
    feature_share_title: 'எங்கும் பகிர்',
    feature_share_desc: 'வாடிக்கையாளர்களை அடைய WhatsApp, Facebook அல்லது எந்த தளத்திலும் உங்கள் பட்டியல் இணைப்பை பகிரவும்.',
    challenges_title: 'நாங்கள் தீர்க்கும் சவால்கள்',
    challenges_subtitle: 'சிறு வணிகங்கள் டிஜிட்டல் ஆவதில் உண்மையான தடைகளை எதிர்கொள்கின்றன',
    challenge_skills_title: 'குறைந்த டிஜிட்டல் திறன்கள்',
    challenge_skills_desc: 'பல கடைக்காரர்கள் தொழில்நுட்பத்தை குழப்பமாக காண்கிறார்கள். சிக்கலான ஆப்ஸ் மற்றும் படிவங்கள் அதிகமாக உள்ளன.',
    challenge_skills_solution: 'எங்கள் குரல்-முதல் அணுகுமுறைக்கு தட்டச்சு அல்லது தொழில்நுட்ப அறிவு தேவையில்லை.',
    challenge_language_title: 'மொழி தடைகள்',
    challenge_language_desc: 'பெரும்பாலான டிஜிட்டல் கருவிகள் ஆங்கிலத்தில் உள்ளன, உள்ளூர் மொழிகளை விரும்பும் மில்லியன் கணக்கானவர்களை விலக்குகின்றன.',
    challenge_language_solution: 'இந்தி, தமிழ், தெலுங்கு, கன்னடம், வங்காளம் மற்றும் ஆங்கிலத்திற்கு முழு ஆதரவு.',
    challenge_presence_title: 'ஆன்லைன் இருப்பு இல்லை',
    challenge_presence_desc: 'பட்டியல் இல்லாமல், வணிகங்கள் புதிய வாடிக்கையாளர்களை ஆன்லைனில் அடையும் வாய்ப்புகளை இழக்கின்றன.',
    challenge_presence_solution: 'நாட்கள் அல்ல, நிமிடங்களில் பகிரக்கூடிய பட்டியல்களை உருவாக்குங்கள்.',
    how_it_works: 'இது எப்படி வேலை செய்கிறது',
    how_it_works_subtitle: '2 நிமிடங்களுக்குள் உங்கள் முதல் தயாரிப்பு பட்டியலை உருவாக்குங்கள்',
    step1_title: 'மொழி தேர்வு',
    step1_desc: '6 இந்திய மொழிகளில் இருந்து உங்கள் விருப்பமான மொழியை தேர்வு செய்யவும்',
    step2_title: 'பொருளை விவரி',
    step2_desc: 'பேசுங்கள், தட்டச்சு செய்யுங்கள் அல்லது உங்கள் பொருளின் புகைப்படம் எடுங்கள்',
    step3_title: 'AI உருவாக்குகிறது',
    step3_desc: 'AI தொழில்முறை பெயர், விவரம் & வகையை உருவாக்குகிறது',
    step4_title: 'பட்டியலை பகிர்',
    step4_desc: 'வாடிக்கையாளர்களுடன் உங்கள் பட்டியல் இணைப்பை பகிரவும்',
    stat_languages: 'ஆதரிக்கப்படும் மொழிகள்',
    stat_inputs: 'உள்ளீட்டு முறைகள்',
    stat_categories: 'தயாரிப்பு வகைகள்',
    stat_products: 'நீங்கள் சேர்க்கக்கூடிய பொருட்கள்',
    cta_title: 'உங்கள் வணிகத்தை டிஜிட்டல் ஆக்க தயாரா?',
    cta_subtitle: 'ஏற்கனவே டிஜிட்டல் கேட்டலாக் ஏஜென்ட் பயன்படுத்தும் ஆயிரக்கணக்கான சிறு வணிகங்களுடன் சேருங்கள். இது இலவசம், எளிதானது மற்றும் உங்கள் மொழியில் வேலை செய்கிறது.',
    cta_button: 'இப்போது உங்கள் பட்டியலை உருவாக்குங்கள்',
    cta_footer: 'டிஜிட்டல் இந்தியா முன்முயற்சியை ஆதரிக்கிறது • பாரதத்திற்காக உருவாக்கப்பட்டது 🇮🇳',
    my_catalog: 'என் பட்டியல்',
    products_count: 'பொருட்கள்',
    publish_platforms: 'தளங்களில் வெளியிடு',
    add_product: 'பொருள் சேர்',
    no_products: 'இன்னும் பொருட்கள் இல்லை. முதல் பொருளை சேர்க்கவும்!',
    add_first: 'முதல் பொருளை சேர்',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    deleting: 'நீக்குகிறது...',
    add_new_product: 'புதிய பொருள் சேர்',
    product_name: 'பொருள் பெயர்',
    description: 'விவரம்',
    category: 'வகை',
    price: 'விலை',
    language: 'மொழி',
    save_product: 'பொருளை சேமி',
    saving: 'சேமிக்கிறது...',
    select_language: 'உங்கள் மொழியை தேர்வு செய்யவும்',
    describe_method: 'உங்கள் பொருளை எப்படி விவரிக்க விரும்புகிறீர்கள்?',
    voice: 'குரல்',
    text: 'உரை',
    camera: 'கேமரா',
    speak_to_describe: 'விவரிக்க பேசுங்கள்',
    type_description: 'விவரத்தை தட்டச்சு செய்யவும்',
    take_a_photo: 'புகைப்படம் எடுங்கள்',
    describe_product: 'உங்கள் பொருளை விவரிக்கவும்',
    describe_placeholder: 'எ.கா., "ராஜஸ்தானில் இருந்து பாரம்பரிய பிளாக் பிரிண்ட் டிசைன் கொண்ட கைவினை பருத்தி புடவை, பண்டிகைகளுக்கு சிறந்தது..."',
    add_description_photo: 'சிறந்த AI முடிவுகளுக்கு விவரத்தை சேர்க்கவும்',
    describe_photo: 'புகைப்படத்தில் என்ன இருக்கிறது என்று விவரிக்கவும்...',
    generate_with_ai: 'AI மூலம் பொருள் விவரங்களை உருவாக்கு',
    ai_generating: 'AI உருவாக்குகிறது...',
    ai_success: '✨ AI உங்கள் குரல் உள்ளீட்டிலிருந்து ஆங்கில பொருள் பட்டியலை உருவாக்கியது! கீழே மதிப்பாய்வு செய்து திருத்தவும்.',
    review_edit: 'மதிப்பாய்வு & திருத்து',
    back_to_input: '← உள்ளீட்டுக்கு திரும்பு',
    product_image: 'பொருள் படம்',
    enter_product_name: 'பொருள் பெயரை உள்ளிடவும்',
    describe_your_product: 'உங்கள் பொருளை விவரிக்கவும்',
    select_category: 'வகையை தேர்வு செய்யவும்',
    enter_price: 'விலையை உள்ளிடவும்',
    cancel: 'ரத்து செய்',
    add_to_catalog: '✓ கேட்டலாக்கில் சேர்',
    adding_product: 'பொருளை சேர்க்கிறது...',
    tip_describe: '💡 குறிப்பு: சிறந்த AI பட்டியல்களுக்கு உங்கள் பொருளை விரிவாக விவரிக்கவும்',
    supports_voice: 'இந்தி, தமிழ், தெலுங்கு, கன்னடம் மற்றும் வங்காளத்தில் குரல் உள்ளீடு ஆதரிக்கப்படுகிறது',
    step_describe: 'விவரி',
    step_review: 'மதிப்பாய்வு & சேமி',
    please_describe: 'முதலில் குரல் அல்லது உரை மூலம் உங்கள் பொருளை விவரிக்கவும்',
    failed_generate: 'பொருள் விவரங்களை உருவாக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    voice_input: 'குரல் உள்ளீடு',
    tap_to_speak: 'பேச தட்டவும்',
    listening: 'கேட்கிறது...',
    stop: 'நிறுத்து',
    take_photo: 'புகைப்படம் எடு',
    upload_image: 'படம் பதிவேற்று',
    capture: 'பிடி',
    retake: 'மீண்டும் எடு',
    use_photo: 'படத்தை பயன்படுத்து',
    publish_title: 'விற்பனை தளங்களில் வெளியிடு',
    publish_subtitle: 'உங்கள் பட்டியலை ஈ-காமர்ஸ் தளங்களுக்கு ஏற்றுமதி செய்யுங்கள்',
    your_catalog: 'உங்கள் பட்டியல்',
    products_ready: 'பொருட்கள் வெளியிட தயார்',
    view_products: 'பொருட்களை பார்',
    share_link: 'பகிரக்கூடிய இணைப்பு',
    share_link_desc: 'வாடிக்கையாளர்களுடன் இந்த இணைப்பை பகிரவும்',
    copy: 'நகலெடு',
    copied: 'நகலெடுக்கப்பட்டது!',
    export: 'ஏற்றுமதி',
    exporting: 'ஏற்றுமதி செய்கிறது...',
    exported: 'ஏற்றுமதி செய்யப்பட்டது',
    share: 'பகிர்',
    login_title: 'மீண்டும் வரவேற்கிறோம்',
    signup_title: 'கணக்கு உருவாக்கு',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    confirm_password: 'கடவுச்சொல்லை உறுதிப்படுத்து',
    full_name: 'முழு பெயர்',
    login_btn: 'உள்நுழை',
    signup_btn: 'பதிவு செய்',
    no_account: 'கணக்கு இல்லையா?',
    have_account: 'ஏற்கனவே கணக்கு உள்ளதா?',
    enter_name: 'உங்கள் பெயரை உள்ளிடவும்',
    enter_email: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    enter_password: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    confirm_password_placeholder: 'உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    password_min: 'குறைந்தது 8 எழுத்துகள்',
    creating_account: 'கணக்கு உருவாக்குகிறது...',
    logging_in: 'உள்நுழைகிறது...',
    login_subtitle: 'உங்கள் பட்டியலை நிர்வகிக்க உள்நுழையவும்',
    signup_subtitle: 'உங்கள் டிஜிட்டல் பட்டியலை உருவாக்க தொடங்குங்கள்',
    something_wrong: 'ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.',
    share_catalog: 'பட்டியலை பகிர்',
    link_copied: 'இணைப்பு நகலெடுக்கப்பட்டது!',
    payment: 'பணம்',
    delete_confirm: 'இந்த பொருளை நீக்க விரும்புகிறீர்களா?',
    failed_load: 'பொருட்களை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    failed_delete: 'பொருளை நீக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    my_catalog_title: 'என் பொருள் பட்டியல்',
    share_catalog_title: 'என் பொருள் பட்டியல்',
    share_catalog_text: 'என் பொருள் பட்டியலை பாருங்கள்!',
    voice_help: 'சொல்லுங்கள்: "டாஷ்போர்டு போ", "பொருள் சேர்", "ஏற்றுமதி செய்", "வெளியேறு"',
    command_recognized: 'கட்டளை அங்கீகரிக்கப்பட்டது',
    command_not_recognized: 'கட்டளை புரியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  },
  te: {
    nav_home: 'హోమ్',
    nav_dashboard: 'నా జాబితా',
    nav_demo: 'డెమో',
    nav_login: 'లాగిన్',
    nav_signup: 'సైన్ అప్',
    nav_logout: 'లాగౌట్',
    hero_title: 'స్థానిక విక్రేతల కోసం AI డిజిటల్ కేటలాగ్',
    hero_subtitle: 'మీ భాషలో వాయిస్ ఉపయోగించి ప్రొఫెషనల్ జాబితాలు సృష్టించండి',
    get_started: 'ఉచితంగా ప్రారంభించండి',
    try_demo: 'డెమో చూడండి',
    my_catalog: 'నా జాబితా',
    products_count: 'ఉత్పత్తులు',
    publish_platforms: 'ప్లాట్‌ఫారమ్‌లలో ప్రచురించండి',
    add_product: 'ఉత్పత్తి జోడించు',
    no_products: 'ఇంకా ఉత్పత్తులు లేవు. మీ మొదటి ఉత్పత్తిని జోడించండి!',
    add_first: 'మొదటి ఉత్పత్తి జోడించు',
    edit: 'సవరించు',
    delete: 'తొలగించు',
    deleting: 'తొలగిస్తోంది...',
    add_new_product: 'కొత్త ఉత్పత్తి జోడించు',
    product_name: 'ఉత్పత్తి పేరు',
    description: 'వివరణ',
    category: 'వర్గం',
    price: 'ధర',
    language: 'భాష',
    save_product: 'ఉత్పత్తి సేవ్ చేయి',
    saving: 'సేవ్ చేస్తోంది...',
    voice_input: 'వాయిస్ ఇన్‌పుట్',
    tap_to_speak: 'మాట్లాడటానికి నొక్కండి',
    listening: 'వింటోంది...',
    stop: 'ఆపు',
    take_photo: 'ఫోటో తీయండి',
    upload_image: 'చిత్రం అప్‌లోడ్ చేయండి',
    capture: 'క్యాప్చర్',
    retake: 'మళ్ళీ తీయండి',
    use_photo: 'ఫోటో ఉపయోగించు',
    publish_title: 'విక్రేత ప్లాట్‌ఫారమ్‌లలో ప్రచురించండి',
    publish_subtitle: 'మీ కేటలాగ్‌ను ఈ-కామర్స్ ప్లాట్‌ఫారమ్‌లకు ఎగుమతి చేయండి',
    your_catalog: 'మీ కేటలాగ్',
    products_ready: 'ఉత్పత్తులు ప్రచురించడానికి సిద్ధంగా ఉన్నాయి',
    view_products: 'ఉత్పత్తులు చూడండి',
    share_link: 'షేర్ చేయగల లింక్',
    share_link_desc: 'కస్టమర్లతో ఈ లింక్ షేర్ చేయండి',
    copy: 'కాపీ',
    copied: 'కాపీ అయింది!',
    export: 'ఎగుమతి',
    exporting: 'ఎగుమతి చేస్తోంది...',
    exported: 'ఎగుమతి అయింది',
    share: 'షేర్',
    login_title: 'తిరిగి స్వాగతం',
    signup_title: 'ఖాతా సృష్టించండి',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    confirm_password: 'పాస్‌వర్డ్ నిర్ధారించండి',
    login_btn: 'లాగిన్',
    signup_btn: 'సైన్ అప్',
    no_account: 'ఖాతా లేదా?',
    have_account: 'ఇప్పటికే ఖాతా ఉందా?',
    voice_help: 'చెప్పండి: "డాష్‌బోర్డ్ వెళ్ళు", "ఉత్పత్తి జోడించు", "ఎగుమతి చేయి", "లాగౌట్"',
    command_recognized: 'ఆదేశం గుర్తించబడింది',
    command_not_recognized: 'ఆదేశం గుర్తించలేదు. మళ్ళీ ప్రయత్నించండి.',
  },
  kn: {
    nav_home: 'ಮುಖಪುಟ',
    nav_dashboard: 'ನನ್ನ ಪಟ್ಟಿ',
    nav_demo: 'ಡೆಮೊ',
    nav_login: 'ಲಾಗಿನ್',
    nav_signup: 'ಸೈನ್ ಅಪ್',
    nav_logout: 'ಲಾಗೌಟ್',
    hero_title: 'ಸ್ಥಳೀಯ ಮಾರಾಟಗಾರರಿಗೆ AI ಡಿಜಿಟಲ್ ಕ್ಯಾಟಲಾಗ್',
    hero_subtitle: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಧ್ವನಿ ಬಳಸಿ ವೃತ್ತಿಪರ ಪಟ್ಟಿಗಳನ್ನು ರಚಿಸಿ',
    get_started: 'ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
    try_demo: 'ಡೆಮೊ ನೋಡಿ',
    my_catalog: 'ನನ್ನ ಪಟ್ಟಿ',
    products_count: 'ಉತ್ಪನ್ನಗಳು',
    publish_platforms: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗಳಲ್ಲಿ ಪ್ರಕಟಿಸಿ',
    add_product: 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    no_products: 'ಇನ್ನೂ ಉತ್ಪನ್ನಗಳಿಲ್ಲ. ನಿಮ್ಮ ಮೊದಲ ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ!',
    add_first: 'ಮೊದಲ ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    deleting: 'ಅಳಿಸುತ್ತಿದೆ...',
    add_new_product: 'ಹೊಸ ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    product_name: 'ಉತ್ಪನ್ನ ಹೆಸರು',
    description: 'ವಿವರಣೆ',
    category: 'ವರ್ಗ',
    price: 'ಬೆಲೆ',
    language: 'ಭಾಷೆ',
    save_product: 'ಉತ್ಪನ್ನ ಉಳಿಸಿ',
    saving: 'ಉಳಿಸುತ್ತಿದೆ...',
    voice_input: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
    tap_to_speak: 'ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    listening: 'ಕೇಳುತ್ತಿದೆ...',
    stop: 'ನಿಲ್ಲಿಸಿ',
    take_photo: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    upload_image: 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    capture: 'ಕ್ಯಾಪ್ಚರ್',
    retake: 'ಮತ್ತೆ ತೆಗೆಯಿರಿ',
    use_photo: 'ಫೋಟೋ ಬಳಸಿ',
    publish_title: 'ಮಾರಾಟ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗಳಲ್ಲಿ ಪ್ರಕಟಿಸಿ',
    publish_subtitle: 'ನಿಮ್ಮ ಕ್ಯಾಟಲಾಗ್ ಅನ್ನು ಇ-ಕಾಮರ್ಸ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗಳಿಗೆ ರಫ್ತು ಮಾಡಿ',
    your_catalog: 'ನಿಮ್ಮ ಕ್ಯಾಟಲಾಗ್',
    products_ready: 'ಉತ್ಪನ್ನಗಳು ಪ್ರಕಟಿಸಲು ಸಿದ್ಧ',
    view_products: 'ಉತ್ಪನ್ನಗಳನ್ನು ನೋಡಿ',
    share_link: 'ಹಂಚಿಕೊಳ್ಳಬಹುದಾದ ಲಿಂಕ್',
    share_link_desc: 'ಗ್ರಾಹಕರೊಂದಿಗೆ ಈ ಲಿಂಕ್ ಹಂಚಿಕೊಳ್ಳಿ',
    copy: 'ನಕಲಿಸಿ',
    copied: 'ನಕಲಿಸಲಾಗಿದೆ!',
    export: 'ರಫ್ತು',
    exporting: 'ರಫ್ತು ಮಾಡುತ್ತಿದೆ...',
    exported: 'ರಫ್ತು ಆಗಿದೆ',
    share: 'ಹಂಚಿಕೊಳ್ಳಿ',
    login_title: 'ಮರಳಿ ಸ್ವಾಗತ',
    signup_title: 'ಖಾತೆ ರಚಿಸಿ',
    email: 'ಇಮೇಲ್',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    confirm_password: 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    login_btn: 'ಲಾಗಿನ್',
    signup_btn: 'ಸೈನ್ ಅಪ್',
    no_account: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    have_account: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    voice_help: 'ಹೇಳಿ: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಹೋಗು", "ಉತ್ಪನ್ನ ಸೇರಿಸು", "ರಫ್ತು ಮಾಡು", "ಲಾಗೌಟ್"',
    command_recognized: 'ಆದೇಶ ಗುರುತಿಸಲಾಗಿದೆ',
    command_not_recognized: 'ಆದೇಶ ಗುರುತಿಸಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  },
  bn: {
    nav_home: 'হোম',
    nav_dashboard: 'আমার তালিকা',
    nav_demo: 'ডেমো',
    nav_login: 'লগইন',
    nav_signup: 'সাইন আপ',
    nav_logout: 'লগআউট',
    hero_title: 'স্থানীয় বিক্রেতাদের জন্য AI ডিজিটাল ক্যাটালগ',
    hero_subtitle: 'আপনার ভাষায় ভয়েস ব্যবহার করে পেশাদার তালিকা তৈরি করুন',
    get_started: 'বিনামূল্যে শুরু করুন',
    try_demo: 'ডেমো দেখুন',
    my_catalog: 'আমার তালিকা',
    products_count: 'পণ্য',
    publish_platforms: 'প্ল্যাটফর্মে প্রকাশ করুন',
    add_product: 'পণ্য যোগ করুন',
    no_products: 'এখনও কোনো পণ্য নেই। আপনার প্রথম পণ্য যোগ করুন!',
    add_first: 'প্রথম পণ্য যোগ করুন',
    edit: 'সম্পাদনা',
    delete: 'মুছুন',
    deleting: 'মুছছে...',
    add_new_product: 'নতুন পণ্য যোগ করুন',
    product_name: 'পণ্যের নাম',
    description: 'বিবরণ',
    category: 'বিভাগ',
    price: 'দাম',
    language: 'ভাষা',
    save_product: 'পণ্য সংরক্ষণ করুন',
    saving: 'সংরক্ষণ করছে...',
    voice_input: 'ভয়েস ইনপুট',
    tap_to_speak: 'কথা বলতে ট্যাপ করুন',
    listening: 'শুনছে...',
    stop: 'থামুন',
    take_photo: 'ছবি তুলুন',
    upload_image: 'ছবি আপলোড করুন',
    capture: 'ক্যাপচার',
    retake: 'আবার তুলুন',
    use_photo: 'ছবি ব্যবহার করুন',
    publish_title: 'বিক্রেতা প্ল্যাটফর্মে প্রকাশ করুন',
    publish_subtitle: 'আপনার ক্যাটালগ ই-কমার্স প্ল্যাটফর্মে রপ্তানি করুন',
    your_catalog: 'আপনার ক্যাটালগ',
    products_ready: 'পণ্য প্রকাশের জন্য প্রস্তুত',
    view_products: 'পণ্য দেখুন',
    share_link: 'শেয়ারযোগ্য লিঙ্ক',
    share_link_desc: 'গ্রাহকদের সাথে এই লিঙ্ক শেয়ার করুন',
    copy: 'কপি',
    copied: 'কপি হয়েছে!',
    export: 'রপ্তানি',
    exporting: 'রপ্তানি করছে...',
    exported: 'রপ্তানি হয়েছে',
    share: 'শেয়ার',
    login_title: 'স্বাগতম',
    signup_title: 'অ্যাকাউন্ট তৈরি করুন',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    confirm_password: 'পাসওয়ার্ড নিশ্চিত করুন',
    login_btn: 'লগইন',
    signup_btn: 'সাইন আপ',
    no_account: 'অ্যাকাউন্ট নেই?',
    have_account: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    voice_help: 'বলুন: "ড্যাশবোর্ড যাও", "পণ্য যোগ করো", "রপ্তানি করো", "লগআউট"',
    command_recognized: 'কমান্ড চিনতে পেরেছে',
    command_not_recognized: 'কমান্ড চিনতে পারেনি। আবার চেষ্টা করুন।',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('appLanguage') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
